-- Telemetry schema v1: observation only; no gameplay authority or retention jobs.
-- All UTC labels are signed epoch microseconds; all elapsed values are unsigned.
CREATE TABLE IF NOT EXISTS telemetry_config (
  environment_id BIGINT UNSIGNED NOT NULL,
  config_id BIGINT UNSIGNED NOT NULL,
  schema_version SMALLINT UNSIGNED NOT NULL,
  revision BIGINT UNSIGNED NOT NULL,
  build_version INT UNSIGNED NOT NULL,
  content_version INT UNSIGNED NOT NULL,
  property_version INT UNSIGNED NOT NULL,
  classifier_version INT UNSIGNED NOT NULL,
  policy_version INT UNSIGNED NOT NULL,
  season_id BIGINT UNSIGNED NOT NULL,
  fingerprint BINARY(32) NOT NULL,
  effective_utc_usec BIGINT NOT NULL,
  interval_usec BIGINT UNSIGNED NOT NULL,
  checkpoint_interval_usec BIGINT UNSIGNED NOT NULL,
  active_window_usec BIGINT UNSIGNED NOT NULL,
  context_segments_per_minute INT UNSIGNED NOT NULL,
  pulse_slot_count SMALLINT UNSIGNED NOT NULL,
  backend TINYINT UNSIGNED NOT NULL,
  enabled TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (environment_id,config_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_session (
  environment_id BIGINT UNSIGNED NOT NULL,
  season_id BIGINT UNSIGNED NOT NULL,
  session_boot_id BIGINT UNSIGNED NOT NULL,
  session_process_id BIGINT UNSIGNED NOT NULL,
  session_seq BIGINT UNSIGNED NOT NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  pid INT NOT NULL,
  latest_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
  connected_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  active_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  idle_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  unknown_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  resident_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  linkdead_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  entered TINYINT UNSIGNED NOT NULL DEFAULT 0,
  exited TINYINT UNSIGNED NOT NULL DEFAULT 0,
  end_reason TINYINT UNSIGNED NOT NULL DEFAULT 0,
  quality_flags INT UNSIGNED NOT NULL DEFAULT 0,
  last_ingest_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (environment_id,season_id,session_boot_id,session_process_id,session_seq),
  UNIQUE KEY uq_telemetry_session_identity (session_boot_id,session_process_id,session_seq),
  KEY idx_telemetry_session_subject (environment_id,season_id,subject_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Tagged fact stream: NULL means the named field is absent for this record kind.
-- An all-zero permitted connection/session is stored as zeros, not SQL NULL.
-- Configuration scope comes from its snapshot; process-wide gaps have zero scope.
CREATE TABLE IF NOT EXISTS telemetry_interval (
  ingest_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  boot_id BIGINT UNSIGNED NOT NULL,
  process_id BIGINT UNSIGNED NOT NULL,
  record_seq BIGINT UNSIGNED NOT NULL,
  schema_version SMALLINT UNSIGNED NOT NULL,
  record_kind TINYINT UNSIGNED NOT NULL,
  occurrence_utc_usec BIGINT NOT NULL,
  ingested_utc_usec BIGINT NOT NULL,
  environment_id BIGINT UNSIGNED NULL,
  season_id BIGINT UNSIGNED NULL,
  session_boot_id BIGINT UNSIGNED NULL,
  session_process_id BIGINT UNSIGNED NULL,
  session_seq BIGINT UNSIGNED NULL,
  subject_id BIGINT UNSIGNED NULL,
  pid INT NULL,
  connection_boot_id BIGINT UNSIGNED NULL,
  connection_process_id BIGINT UNSIGNED NULL,
  connection_seq BIGINT UNSIGNED NULL,
  start_monotonic_usec BIGINT UNSIGNED NULL,
  end_monotonic_usec BIGINT UNSIGNED NULL,
  start_utc_usec BIGINT NULL,
  end_utc_usec BIGINT NULL,
  duration_usec BIGINT UNSIGNED NULL,
  category TINYINT UNSIGNED NULL,
  context TINYINT UNSIGNED NULL,
  context_quality TINYINT UNSIGNED NULL,
  level_band SMALLINT UNSIGNED NULL,
  class_id SMALLINT UNSIGNED NULL,
  race_id SMALLINT UNSIGNED NULL,
  faction_id SMALLINT UNSIGNED NULL,
  zone_vnum INT NULL,
  group_size INT UNSIGNED NULL,
  config_id BIGINT UNSIGNED NULL,
  classifier_version INT UNSIGNED NULL,
  policy_version INT UNSIGNED NULL,
  quality_flags INT UNSIGNED NULL,
  lifecycle TINYINT UNSIGNED NULL,
  end_reason TINYINT UNSIGNED NULL,
  at_monotonic_usec BIGINT UNSIGNED NULL,
  at_utc_usec BIGINT NULL,
  checkpoint_revision BIGINT UNSIGNED NULL,
  connected_usec BIGINT UNSIGNED NULL,
  active_usec BIGINT UNSIGNED NULL,
  idle_usec BIGINT UNSIGNED NULL,
  unknown_usec BIGINT UNSIGNED NULL,
  resident_usec BIGINT UNSIGNED NULL,
  linkdead_usec BIGINT UNSIGNED NULL,
  gap_reason TINYINT UNSIGNED NULL,
  first_missing_record_seq BIGINT UNSIGNED NULL,
  last_missing_record_seq BIGINT UNSIGNED NULL,
  dropped_records BIGINT UNSIGNED NULL,
  config_revision BIGINT UNSIGNED NULL,
  build_version INT UNSIGNED NULL,
  content_version INT UNSIGNED NULL,
  property_version INT UNSIGNED NULL,
  fingerprint BINARY(32) NULL,
  effective_utc_usec BIGINT NULL,
  interval_usec BIGINT UNSIGNED NULL,
  checkpoint_interval_usec BIGINT UNSIGNED NULL,
  active_window_usec BIGINT UNSIGNED NULL,
  context_segments_per_minute INT UNSIGNED NULL,
  pulse_slot_count SMALLINT UNSIGNED NULL,
  backend TINYINT UNSIGNED NULL,
  enabled TINYINT UNSIGNED NULL,
  PRIMARY KEY (ingest_id),
  UNIQUE KEY uq_telemetry_replay (boot_id,process_id,record_seq),
  KEY idx_telemetry_checkpoint (environment_id,season_id,session_boot_id,session_process_id,session_seq,checkpoint_revision),
  KEY idx_telemetry_subject (environment_id,season_id,subject_id,ingest_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_player_day (
  definition_version INT UNSIGNED NOT NULL,
  generation BIGINT UNSIGNED NOT NULL,
  environment_id BIGINT UNSIGNED NOT NULL,
  season_id BIGINT UNSIGNED NOT NULL,
  utc_day DATE NOT NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  session_boot_id BIGINT UNSIGNED NOT NULL,
  session_process_id BIGINT UNSIGNED NOT NULL,
  session_seq BIGINT UNSIGNED NOT NULL,
  connected_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  active_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  idle_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  unknown_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  resident_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  linkdead_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  attributable_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  observed_intervals BIGINT UNSIGNED NOT NULL DEFAULT 0,
  quality_flags INT UNSIGNED NOT NULL DEFAULT 0,
  input_watermark BIGINT UNSIGNED NOT NULL DEFAULT 0,
  provisional TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (definition_version,generation,environment_id,season_id,utc_day,subject_id,session_boot_id,session_process_id,session_seq)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_cohort_day (
  definition_version INT UNSIGNED NOT NULL,
  generation BIGINT UNSIGNED NOT NULL,
  environment_id BIGINT UNSIGNED NOT NULL,
  season_id BIGINT UNSIGNED NOT NULL,
  utc_day DATE NOT NULL,
  level_band SMALLINT UNSIGNED NOT NULL,
  class_id SMALLINT UNSIGNED NOT NULL,
  race_id SMALLINT UNSIGNED NOT NULL,
  faction_id SMALLINT UNSIGNED NOT NULL,
  zone_vnum INT NOT NULL,
  config_id BIGINT UNSIGNED NOT NULL,
  category TINYINT UNSIGNED NOT NULL,
  duration_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  attributable_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
  observed_intervals BIGINT UNSIGNED NOT NULL DEFAULT 0,
  subject_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  session_count BIGINT UNSIGNED NOT NULL DEFAULT 0,
  quality_flags INT UNSIGNED NOT NULL DEFAULT 0,
  input_watermark BIGINT UNSIGNED NOT NULL DEFAULT 0,
  provisional TINYINT UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (definition_version,generation,environment_id,season_id,utc_day,level_band,class_id,race_id,faction_id,zone_vnum,config_id,category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_state (
  definition_version INT UNSIGNED NOT NULL,
  generation BIGINT UNSIGNED NOT NULL,
  environment_id BIGINT UNSIGNED NOT NULL,
  season_id BIGINT UNSIGNED NOT NULL,
  input_watermark BIGINT UNSIGNED NOT NULL DEFAULT 0,
  publication_status TINYINT UNSIGNED NOT NULL DEFAULT 0,
  coverage_start_utc_usec BIGINT NULL,
  coverage_end_utc_usec BIGINT NULL,
  quality_flags INT UNSIGNED NOT NULL DEFAULT 0,
  provisional TINYINT UNSIGNED NOT NULL DEFAULT 1,
  rebuild_from_ingest_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  rebuild_through_ingest_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (definition_version,generation,environment_id,season_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
