-- Additive rollup support stores; facts and existing telemetry projections remain immutable.
-- Checkpoint totals stay separate from interval coverage and cohort membership is exact.
CREATE TABLE IF NOT EXISTS telemetry_rollup_session (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    session_boot_id BIGINT UNSIGNED NOT NULL,
    session_process_id BIGINT UNSIGNED NOT NULL,
    session_seq BIGINT UNSIGNED NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    pid INT NOT NULL,
    latest_checkpoint_revision BIGINT UNSIGNED NOT NULL DEFAULT 0,
    connected_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    active_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    idle_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    unknown_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    resident_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    linkdead_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    covered_connected_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    covered_active_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    covered_idle_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    covered_unknown_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    covered_resident_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    covered_linkdead_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    attributable_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    observed_intervals BIGINT UNSIGNED NOT NULL DEFAULT 0,
    entered TINYINT UNSIGNED NOT NULL DEFAULT 0,
    exited TINYINT UNSIGNED NOT NULL DEFAULT 0,
    end_reason TINYINT UNSIGNED NOT NULL DEFAULT 0,
    quality_flags INT UNSIGNED NOT NULL DEFAULT 0,
    input_watermark BIGINT UNSIGNED NOT NULL DEFAULT 0,
    provisional TINYINT UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,session_boot_id,session_process_id,session_seq),
    KEY idx_rollup_session_subject (definition_version,generation,environment_id,season_id,subject_id,session_boot_id,session_process_id,session_seq)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_cohort_member (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    utc_day DATE NOT NULL,
    level_band SMALLINT UNSIGNED NOT NULL,
    class_id SMALLINT UNSIGNED NOT NULL,
    race_id SMALLINT UNSIGNED NOT NULL,
    faction_id SMALLINT UNSIGNED NOT NULL,
    zone_vnum INT NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    category TINYINT UNSIGNED NOT NULL,
    membership_kind TINYINT UNSIGNED NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    session_boot_id BIGINT UNSIGNED NOT NULL,
    session_process_id BIGINT UNSIGNED NOT NULL,
    session_seq BIGINT UNSIGNED NOT NULL,
    duration_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    attributable_usec BIGINT UNSIGNED NOT NULL DEFAULT 0,
    observed_intervals BIGINT UNSIGNED NOT NULL DEFAULT 0,
    quality_flags INT UNSIGNED NOT NULL DEFAULT 0,
    input_watermark BIGINT UNSIGNED NOT NULL DEFAULT 0,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,utc_day,level_band,class_id,race_id,faction_id,zone_vnum,config_id,category,subject_id,session_boot_id,session_process_id,session_seq),
    CONSTRAINT chk_telemetry_cohort_member_kind CHECK ((membership_kind = 1 AND session_boot_id = 0 AND session_process_id = 0 AND session_seq = 0) OR (membership_kind = 2 AND session_boot_id <> 0 AND session_process_id <> 0 AND session_seq <> 0)),
    CONSTRAINT chk_telemetry_cohort_member_subject CHECK (subject_id <> 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
