#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?DB_HOST is required}" "${DB_USER:?DB_USER is required}" "${DB_PASSWD:?DB_PASSWD is required}" "${DB_NAME:?DB_NAME is required}"
export MYSQL_PWD="$DB_PASSWD"
MYSQL_BIN=${MYSQL_BIN:-mysql}
if "$MYSQL_BIN" --help 2>&1 | grep -- '--ssl-mode' >/dev/null; then MYSQL_SSL=(--ssl-mode=PREFERRED); else MYSQL_SSL=(--skip-ssl); fi
MYSQL=("$MYSQL_BIN" "${MYSQL_SSL[@]}" -h "$DB_HOST" -P "${DB_PORT:-3306}" -u "$DB_USER" -N -B "$DB_NAME")
check() {
    local table=$1 kind=$2 expected=$3 sql=$4 actual
    actual=$("${MYSQL[@]}" -e "SET SESSION group_concat_max_len=16384; $sql")
    if [[ "$actual" != "$expected" ]]; then
        printf 'FAILED: %s %s differs\nexpected: %s\nactual: %s\n' "$table" "$kind" "$expected" "$actual" >&2
        exit 1
    fi
}
check player_death_restitution_receipt engine InnoDB:utf8mb4_unicode_ci 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_receipt'"'"';'
check player_death_restitution_receipt columns 'restitution_id:binary(16):NO:<null>:|source_pid:int:NO:<null>:|death_revision:bigint unsigned:NO:<null>:|recipient_pid:int:NO:<null>:|death_operation_id:binary(16):NO:<null>:|evidence_digest:binary(32):NO:<null>:|plan_digest:binary(32):NO:<null>:|status:tinyint unsigned:NO:1:|actor:varchar(128):NO:<null>:|reason:varchar(255):NO:<null>:|candidate_count:smallint unsigned:NO:0:|delivered_count:smallint unsigned:NO:0:|unresolved_count:smallint unsigned:NO:0:|created_at:timestamp(6):NO:current_timestamp(6):|approved_at:timestamp(6):NO:current_timestamp(6):|applied_at:timestamp(6):YES:<null>:|verified_at:timestamp(6):YES:<null>:' 'SELECT GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(column_type),'"'"'bigint(20)'"'"','"'"'bigint'"'"'),'"'"'int(10)'"'"','"'"'int'"'"'),'"'"'int(11)'"'"','"'"'int'"'"'),'"'"'smallint(5)'"'"','"'"'smallint'"'"'),'"'"'tinyint(3)'"'"','"'"'tinyint'"'"'),'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(NULLIF(LOWER(TRIM(BOTH CHAR(39) FROM column_default)),'"'"'null'"'"'),'"'"'<null>'"'"'),'"'"':'"'"',TRIM(REPLACE(LOWER(extra),'"'"'default_generated'"'"','"'"''"'"'))) ORDER BY ordinal_position SEPARATOR '"'"'|'"'"') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_receipt'"'"';'
check player_death_restitution_receipt indexes 'PRIMARY:0:restitution_id:BTREE|idx_restitution_operation:1:death_operation_id:BTREE|idx_restitution_source:1:source_pid,death_revision:BTREE|uq_restitution_plan:0:source_pid,death_revision,recipient_pid,plan_digest:BTREE' 'SELECT GROUP_CONCAT(CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',cols,'"'"':'"'"',index_type) ORDER BY BINARY index_name SEPARATOR '"'"'|'"'"') FROM (SELECT index_name,non_unique,index_type,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_receipt'"'"' GROUP BY index_name,non_unique,index_type) s;'
check player_death_restitution_receipt foreign_keys '' 'SELECT COALESCE(GROUP_CONCAT(CONCAT(f.constraint_name,'"'"':'"'"',f.cols,'"'"':'"'"',f.referenced_table_name,'"'"':'"'"',f.refcols,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',IF(f.referenced_table_schema=DATABASE(),'"'"'SELF'"'"',f.referenced_table_schema)) ORDER BY BINARY f.constraint_name SEPARATOR '"'"'|'"'"'),'"'"''"'"') FROM (SELECT constraint_name,referenced_table_name,referenced_table_schema,GROUP_CONCAT(column_name ORDER BY ordinal_position) cols,GROUP_CONCAT(referenced_column_name ORDER BY ordinal_position) refcols FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_receipt'"'"' AND referenced_table_name IS NOT NULL GROUP BY constraint_name,referenced_table_name,referenced_table_schema) f JOIN information_schema.referential_constraints r ON r.constraint_schema=DATABASE() AND r.table_name='"'"'player_death_restitution_receipt'"'"' AND r.constraint_name=f.constraint_name;'
check player_death_restitution_item engine InnoDB:utf8mb4_unicode_ci 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_item'"'"';'
check player_death_restitution_item columns 'restitution_id:binary(16):NO:<null>:|item_uid:bigint unsigned:NO:<null>:|source_root_item_uid:bigint unsigned:NO:0:|source_parent_item_uid:bigint unsigned:NO:0:|delivered_root_item_uid:bigint unsigned:NO:0:|delivered_parent_item_uid:bigint unsigned:NO:0:|source_item_revision:bigint unsigned:NO:0:|delivered_item_revision:bigint unsigned:NO:0:|vnum:int:NO:0:|artifact_vnum:int:NO:0:|disposition:tinyint unsigned:NO:<null>:|classification:varchar(64):NO:<null>:|metadata_digest:binary(32):YES:<null>:|metadata_payload:mediumblob:YES:<null>:|note:varchar(255):NO::|artifact_loss_epoch:bigint unsigned:NO:0:|artifact_source_timer_epoch:bigint unsigned:NO:0:|artifact_usable_lifetime_seconds:bigint unsigned:NO:0:|artifact_delivered_timer_epoch:bigint unsigned:NO:0:|artifact_timing_basis:varchar(64):NO::|artifact_compensation_reference:varchar(255):NO::' 'SELECT GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(column_type),'"'"'bigint(20)'"'"','"'"'bigint'"'"'),'"'"'int(10)'"'"','"'"'int'"'"'),'"'"'int(11)'"'"','"'"'int'"'"'),'"'"'smallint(5)'"'"','"'"'smallint'"'"'),'"'"'tinyint(3)'"'"','"'"'tinyint'"'"'),'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(NULLIF(LOWER(TRIM(BOTH CHAR(39) FROM column_default)),'"'"'null'"'"'),'"'"'<null>'"'"'),'"'"':'"'"',TRIM(REPLACE(LOWER(extra),'"'"'default_generated'"'"','"'"''"'"'))) ORDER BY ordinal_position SEPARATOR '"'"'|'"'"') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_item'"'"';'
check player_death_restitution_item indexes 'PRIMARY:0:restitution_id,item_uid:BTREE|idx_restitution_item_uid:1:item_uid:BTREE' 'SELECT GROUP_CONCAT(CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',cols,'"'"':'"'"',index_type) ORDER BY BINARY index_name SEPARATOR '"'"'|'"'"') FROM (SELECT index_name,non_unique,index_type,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_item'"'"' GROUP BY index_name,non_unique,index_type) s;'
check player_death_restitution_item foreign_keys restitution_item_receipt_fk:restitution_id:player_death_restitution_receipt:restitution_id:RESTRICT:RESTRICT:SELF 'SELECT COALESCE(GROUP_CONCAT(CONCAT(f.constraint_name,'"'"':'"'"',f.cols,'"'"':'"'"',f.referenced_table_name,'"'"':'"'"',f.refcols,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',IF(f.referenced_table_schema=DATABASE(),'"'"'SELF'"'"',f.referenced_table_schema)) ORDER BY BINARY f.constraint_name SEPARATOR '"'"'|'"'"'),'"'"''"'"') FROM (SELECT constraint_name,referenced_table_name,referenced_table_schema,GROUP_CONCAT(column_name ORDER BY ordinal_position) cols,GROUP_CONCAT(referenced_column_name ORDER BY ordinal_position) refcols FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_item'"'"' AND referenced_table_name IS NOT NULL GROUP BY constraint_name,referenced_table_name,referenced_table_schema) f JOIN information_schema.referential_constraints r ON r.constraint_schema=DATABASE() AND r.table_name='"'"'player_death_restitution_item'"'"' AND r.constraint_name=f.constraint_name;'
check player_death_restitution_delivery engine InnoDB:utf8mb4_unicode_ci 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_delivery'"'"';'
check player_death_restitution_delivery columns 'item_uid:bigint unsigned:NO:<null>:|restitution_id:binary(16):NO:<null>:|source_pid:int:NO:<null>:|death_revision:bigint unsigned:NO:<null>:|recipient_pid:int:NO:<null>:|source_item_revision:bigint unsigned:NO:<null>:|delivered_item_revision:bigint unsigned:NO:<null>:|delivered_item_id:int unsigned:NO:<null>:|metadata_digest:binary(32):NO:<null>:|original_payload:mediumblob:NO:<null>:|delivered_at:timestamp(6):NO:current_timestamp(6):' 'SELECT GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(column_type),'"'"'bigint(20)'"'"','"'"'bigint'"'"'),'"'"'int(10)'"'"','"'"'int'"'"'),'"'"'int(11)'"'"','"'"'int'"'"'),'"'"'smallint(5)'"'"','"'"'smallint'"'"'),'"'"'tinyint(3)'"'"','"'"'tinyint'"'"'),'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(NULLIF(LOWER(TRIM(BOTH CHAR(39) FROM column_default)),'"'"'null'"'"'),'"'"'<null>'"'"'),'"'"':'"'"',TRIM(REPLACE(LOWER(extra),'"'"'default_generated'"'"','"'"''"'"'))) ORDER BY ordinal_position SEPARATOR '"'"'|'"'"') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_delivery'"'"';'
check player_death_restitution_delivery indexes 'PRIMARY:0:item_uid:BTREE|idx_restitution_delivery_receipt:1:restitution_id:BTREE|idx_restitution_delivery_recipient:1:recipient_pid,item_uid:BTREE|uq_restitution_delivery_receipt_item:0:restitution_id,item_uid:BTREE' 'SELECT GROUP_CONCAT(CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',cols,'"'"':'"'"',index_type) ORDER BY BINARY index_name SEPARATOR '"'"'|'"'"') FROM (SELECT index_name,non_unique,index_type,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_delivery'"'"' GROUP BY index_name,non_unique,index_type) s;'
check player_death_restitution_delivery foreign_keys restitution_delivery_receipt_fk:restitution_id,item_uid:player_death_restitution_item:restitution_id,item_uid:RESTRICT:RESTRICT:SELF 'SELECT COALESCE(GROUP_CONCAT(CONCAT(f.constraint_name,'"'"':'"'"',f.cols,'"'"':'"'"',f.referenced_table_name,'"'"':'"'"',f.refcols,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',IF(f.referenced_table_schema=DATABASE(),'"'"'SELF'"'"',f.referenced_table_schema)) ORDER BY BINARY f.constraint_name SEPARATOR '"'"'|'"'"'),'"'"''"'"') FROM (SELECT constraint_name,referenced_table_name,referenced_table_schema,GROUP_CONCAT(column_name ORDER BY ordinal_position) cols,GROUP_CONCAT(referenced_column_name ORDER BY ordinal_position) refcols FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_delivery'"'"' AND referenced_table_name IS NOT NULL GROUP BY constraint_name,referenced_table_name,referenced_table_schema) f JOIN information_schema.referential_constraints r ON r.constraint_schema=DATABASE() AND r.table_name='"'"'player_death_restitution_delivery'"'"' AND r.constraint_name=f.constraint_name;'
check player_death_restitution_runtime engine InnoDB:utf8mb4_unicode_ci 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_runtime'"'"';'
check player_death_restitution_runtime columns 'item_uid:bigint unsigned:NO:<null>:|recipient_pid:int:NO:<null>:|state_payload:mediumblob:NO:<null>:|state_digest:binary(32):NO:<null>:|updated_at:timestamp(6):NO:current_timestamp(6):on update current_timestamp(6)' 'SELECT GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LOWER(column_type),'"'"'bigint(20)'"'"','"'"'bigint'"'"'),'"'"'int(10)'"'"','"'"'int'"'"'),'"'"'int(11)'"'"','"'"'int'"'"'),'"'"'smallint(5)'"'"','"'"'smallint'"'"'),'"'"'tinyint(3)'"'"','"'"'tinyint'"'"'),'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(NULLIF(LOWER(TRIM(BOTH CHAR(39) FROM column_default)),'"'"'null'"'"'),'"'"'<null>'"'"'),'"'"':'"'"',TRIM(REPLACE(LOWER(extra),'"'"'default_generated'"'"','"'"''"'"'))) ORDER BY ordinal_position SEPARATOR '"'"'|'"'"') FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_runtime'"'"';'
check player_death_restitution_runtime indexes 'PRIMARY:0:item_uid:BTREE|idx_restitution_runtime_recipient:1:recipient_pid,item_uid:BTREE' 'SELECT GROUP_CONCAT(CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',cols,'"'"':'"'"',index_type) ORDER BY BINARY index_name SEPARATOR '"'"'|'"'"') FROM (SELECT index_name,non_unique,index_type,GROUP_CONCAT(column_name ORDER BY seq_in_index) cols FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_runtime'"'"' GROUP BY index_name,non_unique,index_type) s;'
check player_death_restitution_runtime foreign_keys restitution_runtime_delivery_fk:item_uid:player_death_restitution_delivery:item_uid:RESTRICT:RESTRICT:SELF 'SELECT COALESCE(GROUP_CONCAT(CONCAT(f.constraint_name,'"'"':'"'"',f.cols,'"'"':'"'"',f.referenced_table_name,'"'"':'"'"',f.refcols,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',IF(f.referenced_table_schema=DATABASE(),'"'"'SELF'"'"',f.referenced_table_schema)) ORDER BY BINARY f.constraint_name SEPARATOR '"'"'|'"'"'),'"'"''"'"') FROM (SELECT constraint_name,referenced_table_name,referenced_table_schema,GROUP_CONCAT(column_name ORDER BY ordinal_position) cols,GROUP_CONCAT(referenced_column_name ORDER BY ordinal_position) refcols FROM information_schema.key_column_usage WHERE table_schema=DATABASE() AND table_name='"'"'player_death_restitution_runtime'"'"' AND referenced_table_name IS NOT NULL GROUP BY constraint_name,referenced_table_name,referenced_table_schema) f JOIN information_schema.referential_constraints r ON r.constraint_schema=DATABASE() AND r.table_name='"'"'player_death_restitution_runtime'"'"' AND r.constraint_name=f.constraint_name;'
printf 'player death restitution exact schema verified\n'
