-- Definition 2 projects collected typed facts using the existing atomic rollup cursor.
-- Observations retain source status; encounters are not shared battles or zone clears.

CREATE TABLE IF NOT EXISTS telemetry_rollup_progression_day (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    utc_day DATE NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    session_boot_id BIGINT UNSIGNED NOT NULL,
    session_process_id BIGINT UNSIGNED NOT NULL,
    session_seq BIGINT UNSIGNED NOT NULL,
    cell_digest BINARY(32) NOT NULL,
    pid INT NOT NULL,
    level SMALLINT UNSIGNED NOT NULL,
    level_band SMALLINT UNSIGNED NOT NULL,
    class_id SMALLINT UNSIGNED NOT NULL,
    race_id SMALLINT UNSIGNED NOT NULL,
    faction_id SMALLINT UNSIGNED NOT NULL,
    zone_vnum INT NOT NULL,
    group_size INT UNSIGNED NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    classifier_version INT UNSIGNED NOT NULL,
    policy_version INT UNSIGNED NOT NULL,
    source TINYINT UNSIGNED NOT NULL,
    reason TINYINT UNSIGNED NOT NULL,
    observation_status TINYINT UNSIGNED NOT NULL,
    modifier_flags INT UNSIGNED NOT NULL,
    observations BIGINT UNSIGNED NOT NULL,
    zero_applied_observations BIGINT UNSIGNED NOT NULL,
    negative_applied_observations BIGINT UNSIGNED NOT NULL,
    requested_xp BIGINT NOT NULL,
    computed_xp BIGINT NOT NULL,
    applied_xp BIGINT NOT NULL,
    earned_positive_xp BIGINT UNSIGNED NOT NULL,
    death_loss_xp BIGINT UNSIGNED NOT NULL,
    restored_positive_xp BIGINT UNSIGNED NOT NULL,
    quality_flags INT UNSIGNED NOT NULL,
    input_watermark BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,utc_day,subject_id,session_boot_id,session_process_id,session_seq,cell_digest),
    CONSTRAINT fk_observation_1_state FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_state (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_observation_1_scope CHECK (definition_version = 2 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0 AND input_watermark <> 0),
    CONSTRAINT chk_observation_1_quality CHECK ((quality_flags & 536806399) = quality_flags),
    CONSTRAINT chk_observation_1_identity CHECK (subject_id <> 0 AND pid > 0 AND session_boot_id <> 0 AND session_process_id <> 0 AND session_seq <> 0),
    CONSTRAINT chk_observation_1_source CHECK (config_id <> 0 AND classifier_version <> 0 AND policy_version <> 0 AND zone_vnum >= -1 AND source BETWEEN 0 AND 12 AND reason BETWEEN 0 AND 6 AND observation_status BETWEEN 1 AND 3 AND modifier_flags <= 511),
    CONSTRAINT chk_observation_1_counts CHECK (observations > 0 AND zero_applied_observations <= observations AND negative_applied_observations <= observations - zero_applied_observations),
    CONSTRAINT chk_observation_1_earned CHECK ((reason = 1 AND source BETWEEN 1 AND 10) OR earned_positive_xp = 0),
    CONSTRAINT chk_observation_1_loss CHECK (reason = 2 OR death_loss_xp = 0),
    CONSTRAINT chk_observation_1_restored CHECK (reason = 3 OR restored_positive_xp = 0),
    CONSTRAINT chk_observation_1_day CHECK (YEAR(utc_day) >= 1000 AND (YEAR(utc_day) <> 1000 OR DAYOFYEAR(utc_day) <> 1 OR (quality_flags & 196608) <> 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_level_event (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    boot_id BIGINT UNSIGNED NOT NULL,
    process_id BIGINT UNSIGNED NOT NULL,
    record_seq BIGINT UNSIGNED NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    pid INT NOT NULL,
    session_boot_id BIGINT UNSIGNED NOT NULL,
    session_process_id BIGINT UNSIGNED NOT NULL,
    session_seq BIGINT UNSIGNED NOT NULL,
    kind TINYINT UNSIGNED NOT NULL,
    source TINYINT UNSIGNED NOT NULL,
    reason TINYINT UNSIGNED NOT NULL,
    observation_status TINYINT UNSIGNED NOT NULL,
    modifier_flags INT UNSIGNED NOT NULL,
    before_level SMALLINT UNSIGNED NOT NULL,
    after_level SMALLINT UNSIGNED NOT NULL,
    threshold_xp BIGINT UNSIGNED NOT NULL,
    at_monotonic_usec BIGINT UNSIGNED NOT NULL,
    occurrence_utc_usec BIGINT NULL,
    level_band SMALLINT UNSIGNED NOT NULL,
    class_id SMALLINT UNSIGNED NOT NULL,
    race_id SMALLINT UNSIGNED NOT NULL,
    faction_id SMALLINT UNSIGNED NOT NULL,
    zone_vnum INT NOT NULL,
    group_size INT UNSIGNED NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    classifier_version INT UNSIGNED NOT NULL,
    policy_version INT UNSIGNED NOT NULL,
    quality_flags INT UNSIGNED NOT NULL,
    input_watermark BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,boot_id,process_id,record_seq),
    CONSTRAINT fk_observation_2_state FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_state (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_observation_2_scope CHECK (definition_version = 2 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0 AND input_watermark <> 0),
    CONSTRAINT chk_observation_2_quality CHECK ((quality_flags & 536806399) = quality_flags),
    CONSTRAINT chk_observation_2_identity CHECK (subject_id <> 0 AND pid > 0 AND session_boot_id <> 0 AND session_process_id <> 0 AND session_seq <> 0 AND boot_id <> 0 AND process_id <> 0 AND record_seq <> 0),
    CONSTRAINT chk_observation_2_source CHECK (config_id <> 0 AND classifier_version <> 0 AND policy_version <> 0 AND zone_vnum >= -1 AND source BETWEEN 0 AND 12 AND reason BETWEEN 0 AND 6 AND observation_status BETWEEN 1 AND 3 AND modifier_flags <= 511),
    CONSTRAINT chk_observation_2_direction CHECK ((kind = 2 AND after_level > before_level) OR (kind = 3 AND after_level < before_level))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_encounter (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    encounter_boot_id BIGINT UNSIGNED NOT NULL,
    encounter_process_id BIGINT UNSIGNED NOT NULL,
    encounter_seq BIGINT UNSIGNED NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    classifier_version INT UNSIGNED NOT NULL,
    policy_version INT UNSIGNED NOT NULL,
    zone_vnum INT NOT NULL,
    group_key BIGINT UNSIGNED NOT NULL,
    start_monotonic_usec BIGINT UNSIGNED NOT NULL,
    start_utc_usec BIGINT NULL,
    start_seen TINYINT UNSIGNED NOT NULL,
    close_seen TINYINT UNSIGNED NOT NULL,
    end_monotonic_usec BIGINT UNSIGNED NULL,
    end_utc_usec BIGINT NULL,
    elapsed_usec BIGINT UNSIGNED NULL,
    outcome TINYINT UNSIGNED NOT NULL,
    mode TINYINT UNSIGNED NOT NULL,
    mode_mask INT UNSIGNED NOT NULL,
    latest_revision SMALLINT UNSIGNED NOT NULL,
    latest_event TINYINT UNSIGNED NOT NULL,
    latest_at_monotonic_usec BIGINT UNSIGNED NOT NULL,
    participant_count SMALLINT UNSIGNED NOT NULL,
    expected_credit_count SMALLINT UNSIGNED NOT NULL,
    source_events BIGINT UNSIGNED NOT NULL,
    quality_flags INT UNSIGNED NOT NULL,
    input_watermark BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,encounter_boot_id,encounter_process_id,encounter_seq),
    CONSTRAINT fk_observation_3_state FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_state (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_observation_3_scope CHECK (definition_version = 2 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0 AND input_watermark <> 0),
    CONSTRAINT chk_observation_3_quality CHECK ((quality_flags & 536806399) = quality_flags),
    CONSTRAINT chk_observation_3_identity CHECK (encounter_boot_id <> 0 AND encounter_process_id <> 0 AND encounter_seq <> 0),
    CONSTRAINT chk_observation_3_source CHECK (config_id <> 0 AND classifier_version <> 0 AND policy_version <> 0 AND zone_vnum >= -1 AND mode BETWEEN 0 AND 3 AND mode_mask BETWEEN 1 AND 15 AND latest_revision > 0 AND latest_event BETWEEN 1 AND 5 AND source_events > 0),
    CONSTRAINT chk_observation_3_anchor CHECK (latest_at_monotonic_usec >= start_monotonic_usec),
    CONSTRAINT chk_observation_3_evidence CHECK (start_seen BETWEEN 0 AND 1 AND close_seen BETWEEN 0 AND 1),
    CONSTRAINT chk_observation_3_closure CHECK ((close_seen = 0 AND end_monotonic_usec IS NULL AND end_utc_usec IS NULL AND elapsed_usec IS NULL AND outcome = 0) OR (close_seen = 1 AND end_monotonic_usec IS NOT NULL AND elapsed_usec IS NOT NULL AND end_monotonic_usec >= start_monotonic_usec AND elapsed_usec = end_monotonic_usec - start_monotonic_usec AND outcome BETWEEN 1 AND 10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_encounter_participant (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    encounter_boot_id BIGINT UNSIGNED NOT NULL,
    encounter_process_id BIGINT UNSIGNED NOT NULL,
    encounter_seq BIGINT UNSIGNED NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    pid INT NOT NULL,
    latest_revision SMALLINT UNSIGNED NOT NULL,
    latest_event TINYINT UNSIGNED NOT NULL,
    latest_at_monotonic_usec BIGINT UNSIGNED NOT NULL,
    effort_revision SMALLINT UNSIGNED NOT NULL,
    participant_usec BIGINT UNSIGNED NULL,
    join_seen TINYINT UNSIGNED NOT NULL,
    leave_seen TINYINT UNSIGNED NOT NULL,
    summary_seen TINYINT UNSIGNED NOT NULL,
    outcome TINYINT UNSIGNED NOT NULL,
    quality_flags INT UNSIGNED NOT NULL,
    input_watermark BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,encounter_boot_id,encounter_process_id,encounter_seq,subject_id,pid),
    CONSTRAINT fk_observation_4_state FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_state (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_observation_4_scope CHECK (definition_version = 2 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0 AND input_watermark <> 0),
    CONSTRAINT chk_observation_4_quality CHECK ((quality_flags & 536806399) = quality_flags),
    CONSTRAINT chk_observation_4_identity CHECK (encounter_boot_id <> 0 AND encounter_process_id <> 0 AND encounter_seq <> 0 AND subject_id <> 0 AND pid > 0),
    CONSTRAINT chk_observation_4_event CHECK (latest_revision > 0 AND latest_event IN (2,3,5) AND effort_revision <= latest_revision),
    CONSTRAINT chk_observation_4_evidence CHECK (join_seen BETWEEN 0 AND 1 AND leave_seen BETWEEN 0 AND 1 AND summary_seen BETWEEN 0 AND 1),
    CONSTRAINT chk_observation_4_effort CHECK ((effort_revision = 0 AND participant_usec IS NULL AND outcome = 0) OR (effort_revision > 0 AND participant_usec IS NOT NULL AND outcome BETWEEN 1 AND 10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_combat_actor (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    encounter_boot_id BIGINT UNSIGNED NOT NULL,
    encounter_process_id BIGINT UNSIGNED NOT NULL,
    encounter_seq BIGINT UNSIGNED NOT NULL,
    actor_kind TINYINT UNSIGNED NOT NULL,
    actor_id BIGINT UNSIGNED NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    classifier_version INT UNSIGNED NOT NULL,
    policy_version INT UNSIGNED NOT NULL,
    zone_vnum INT NOT NULL,
    group_key BIGINT UNSIGNED NOT NULL,
    actor_pid INT NOT NULL,
    owner_subject_id BIGINT UNSIGNED NOT NULL,
    revision SMALLINT UNSIGNED NOT NULL,
    mode TINYINT UNSIGNED NOT NULL,
    outcome TINYINT UNSIGNED NOT NULL,
    start_monotonic_usec BIGINT UNSIGNED NOT NULL,
    end_monotonic_usec BIGINT UNSIGNED NOT NULL,
    start_utc_usec BIGINT NULL,
    end_utc_usec BIGINT NULL,
    unique_player_count SMALLINT UNSIGNED NOT NULL,
    participant_count SMALLINT UNSIGNED NOT NULL,
    dropped_participant_count SMALLINT UNSIGNED NOT NULL,
    power_band SMALLINT UNSIGNED NOT NULL,
    opponent_power_band SMALLINT UNSIGNED NOT NULL,
    opponent_count SMALLINT UNSIGNED NOT NULL,
    modifier_flags INT UNSIGNED NOT NULL,
    damage_dealt BIGINT UNSIGNED NOT NULL,
    damage_taken BIGINT UNSIGNED NOT NULL,
    healing_attempted BIGINT UNSIGNED NOT NULL,
    effective_healing BIGINT UNSIGNED NOT NULL,
    overhealing BIGINT UNSIGNED NOT NULL,
    control_applications BIGINT UNSIGNED NOT NULL,
    casting_attempts BIGINT UNSIGNED NOT NULL,
    casting_completions BIGINT UNSIGNED NOT NULL,
    casting_aborts BIGINT UNSIGNED NOT NULL,
    casting_elapsed_usec BIGINT UNSIGNED NOT NULL,
    tanking_usec BIGINT UNSIGNED NOT NULL,
    quality_flags INT UNSIGNED NOT NULL,
    input_watermark BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,encounter_boot_id,encounter_process_id,encounter_seq,actor_kind,actor_id),
    CONSTRAINT fk_observation_5_state FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_state (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_observation_5_scope CHECK (definition_version = 2 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0 AND input_watermark <> 0),
    CONSTRAINT chk_observation_5_quality CHECK ((quality_flags & 536806399) = quality_flags),
    CONSTRAINT chk_observation_5_identity CHECK (encounter_boot_id <> 0 AND encounter_process_id <> 0 AND encounter_seq <> 0 AND actor_id <> 0),
    CONSTRAINT chk_observation_5_source CHECK (config_id <> 0 AND classifier_version <> 0 AND policy_version <> 0 AND zone_vnum >= -1 AND revision > 0 AND mode BETWEEN 1 AND 3 AND outcome BETWEEN 1 AND 10 AND modifier_flags <= 255),
    CONSTRAINT chk_observation_5_owner CHECK ((actor_kind = 1 AND actor_pid > 0 AND owner_subject_id = actor_id) OR (actor_kind = 2 AND actor_pid = -1 AND owner_subject_id <> 0) OR (actor_kind = 3 AND actor_pid = -1 AND owner_subject_id = 0)),
    CONSTRAINT chk_observation_5_window CHECK (end_monotonic_usec >= start_monotonic_usec),
    CONSTRAINT chk_observation_5_counts CHECK (unique_player_count <= 64 AND participant_count <= 64),
    CONSTRAINT chk_observation_5_healing CHECK (effective_healing <= healing_attempted),
    CONSTRAINT chk_observation_5_casting CHECK (casting_completions <= casting_attempts AND casting_aborts <= casting_attempts - casting_completions)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
