#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_progression_day' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|utc_day:date:NO:NULL:|subject_id:bigint unsigned:NO:NULL:|session_boot_id:bigint unsigned:NO:NULL:|session_process_id:bigint unsigned:NO:NULL:|session_seq:bigint unsigned:NO:NULL:|cell_digest:binary(32):NO:NULL:|pid:int:NO:NULL:|level:smallint unsigned:NO:NULL:|level_band:smallint unsigned:NO:NULL:|class_id:smallint unsigned:NO:NULL:|race_id:smallint unsigned:NO:NULL:|faction_id:smallint unsigned:NO:NULL:|zone_vnum:int:NO:NULL:|group_size:int unsigned:NO:NULL:|config_id:bigint unsigned:NO:NULL:|classifier_version:int unsigned:NO:NULL:|policy_version:int unsigned:NO:NULL:|source:tinyint unsigned:NO:NULL:|reason:tinyint unsigned:NO:NULL:|observation_status:tinyint unsigned:NO:NULL:|modifier_flags:int unsigned:NO:NULL:|observations:bigint unsigned:NO:NULL:|zero_applied_observations:bigint unsigned:NO:NULL:|negative_applied_observations:bigint unsigned:NO:NULL:|requested_xp:bigint:NO:NULL:|computed_xp:bigint:NO:NULL:|applied_xp:bigint:NO:NULL:|earned_positive_xp:bigint unsigned:NO:NULL:|death_loss_xp:bigint unsigned:NO:NULL:|restored_positive_xp:bigint unsigned:NO:NULL:|quality_flags:int unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_progression_day columns differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_progression_day' GROUP BY index_name,non_unique,index_type ORDER BY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,utc_day:0,subject_id:0,session_boot_id:0,session_process_id:0,session_seq:0,cell_digest:0' ]] || { echo 'telemetry_rollup_progression_day indexes differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT engine FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_progression_day';")
[[ "$engine" == InnoDB ]] || { echo 'telemetry_rollup_progression_day engine differs' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_progression_day' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_observation_1_counts|chk_observation_1_day|chk_observation_1_earned|chk_observation_1_identity|chk_observation_1_loss|chk_observation_1_quality|chk_observation_1_restored|chk_observation_1_scope|chk_observation_1_source|fk_observation_1_state' ]] || { echo 'telemetry_rollup_progression_day constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),''))) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_progression_day' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_observation_1_counts:observations>0andzero_applied_observations<=observationsandnegative_applied_observations<=observations-zero_applied_observations|chk_observation_1_day:yearutc_day>=1000andyearutc_day<>1000ordayofyearutc_day<>1orquality_flags&196608<>0|chk_observation_1_earned:reason=1andsourcebetween1and10orearned_positive_xp=0|chk_observation_1_identity:subject_id<>0andpid>0andsession_boot_id<>0andsession_process_id<>0andsession_seq<>0|chk_observation_1_loss:reason=2ordeath_loss_xp=0|chk_observation_1_quality:quality_flags&536806399=quality_flags|chk_observation_1_restored:reason=3orrestored_positive_xp=0|chk_observation_1_scope:definition_version=2andgeneration<>0andenvironment_id<>0andseason_id<>0andinput_watermark<>0|chk_observation_1_source:config_id<>0andclassifier_version<>0andpolicy_version<>0andzone_vnum>=-1andsourcebetween0and12andreasonbetween0and6andobservation_statusbetween1and3andmodifier_flags<=511' ]] || { echo 'telemetry_rollup_progression_day checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_progression_day' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_observation_1_state:1:definition_version:telemetry_rollup_state:definition_version:RESTRICT:RESTRICT:1|fk_observation_1_state:2:generation:telemetry_rollup_state:generation:RESTRICT:RESTRICT:1|fk_observation_1_state:3:environment_id:telemetry_rollup_state:environment_id:RESTRICT:RESTRICT:1|fk_observation_1_state:4:season_id:telemetry_rollup_state:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_progression_day foreign keys differ' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_level_event' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|boot_id:bigint unsigned:NO:NULL:|process_id:bigint unsigned:NO:NULL:|record_seq:bigint unsigned:NO:NULL:|subject_id:bigint unsigned:NO:NULL:|pid:int:NO:NULL:|session_boot_id:bigint unsigned:NO:NULL:|session_process_id:bigint unsigned:NO:NULL:|session_seq:bigint unsigned:NO:NULL:|kind:tinyint unsigned:NO:NULL:|source:tinyint unsigned:NO:NULL:|reason:tinyint unsigned:NO:NULL:|observation_status:tinyint unsigned:NO:NULL:|modifier_flags:int unsigned:NO:NULL:|before_level:smallint unsigned:NO:NULL:|after_level:smallint unsigned:NO:NULL:|threshold_xp:bigint unsigned:NO:NULL:|at_monotonic_usec:bigint unsigned:NO:NULL:|occurrence_utc_usec:bigint:YES:NULL:|level_band:smallint unsigned:NO:NULL:|class_id:smallint unsigned:NO:NULL:|race_id:smallint unsigned:NO:NULL:|faction_id:smallint unsigned:NO:NULL:|zone_vnum:int:NO:NULL:|group_size:int unsigned:NO:NULL:|config_id:bigint unsigned:NO:NULL:|classifier_version:int unsigned:NO:NULL:|policy_version:int unsigned:NO:NULL:|quality_flags:int unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_level_event columns differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_level_event' GROUP BY index_name,non_unique,index_type ORDER BY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,boot_id:0,process_id:0,record_seq:0' ]] || { echo 'telemetry_rollup_level_event indexes differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT engine FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_level_event';")
[[ "$engine" == InnoDB ]] || { echo 'telemetry_rollup_level_event engine differs' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_level_event' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_observation_2_direction|chk_observation_2_identity|chk_observation_2_quality|chk_observation_2_scope|chk_observation_2_source|fk_observation_2_state' ]] || { echo 'telemetry_rollup_level_event constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),''))) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_level_event' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_observation_2_direction:kind=2andafter_level>before_levelorkind=3andafter_level<before_level|chk_observation_2_identity:subject_id<>0andpid>0andsession_boot_id<>0andsession_process_id<>0andsession_seq<>0andboot_id<>0andprocess_id<>0andrecord_seq<>0|chk_observation_2_quality:quality_flags&536806399=quality_flags|chk_observation_2_scope:definition_version=2andgeneration<>0andenvironment_id<>0andseason_id<>0andinput_watermark<>0|chk_observation_2_source:config_id<>0andclassifier_version<>0andpolicy_version<>0andzone_vnum>=-1andsourcebetween0and12andreasonbetween0and6andobservation_statusbetween1and3andmodifier_flags<=511' ]] || { echo 'telemetry_rollup_level_event checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_level_event' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_observation_2_state:1:definition_version:telemetry_rollup_state:definition_version:RESTRICT:RESTRICT:1|fk_observation_2_state:2:generation:telemetry_rollup_state:generation:RESTRICT:RESTRICT:1|fk_observation_2_state:3:environment_id:telemetry_rollup_state:environment_id:RESTRICT:RESTRICT:1|fk_observation_2_state:4:season_id:telemetry_rollup_state:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_level_event foreign keys differ' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_encounter' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|encounter_boot_id:bigint unsigned:NO:NULL:|encounter_process_id:bigint unsigned:NO:NULL:|encounter_seq:bigint unsigned:NO:NULL:|config_id:bigint unsigned:NO:NULL:|classifier_version:int unsigned:NO:NULL:|policy_version:int unsigned:NO:NULL:|zone_vnum:int:NO:NULL:|group_key:bigint unsigned:NO:NULL:|start_monotonic_usec:bigint unsigned:NO:NULL:|start_utc_usec:bigint:YES:NULL:|start_seen:tinyint unsigned:NO:NULL:|close_seen:tinyint unsigned:NO:NULL:|end_monotonic_usec:bigint unsigned:YES:NULL:|end_utc_usec:bigint:YES:NULL:|elapsed_usec:bigint unsigned:YES:NULL:|outcome:tinyint unsigned:NO:NULL:|mode:tinyint unsigned:NO:NULL:|mode_mask:int unsigned:NO:NULL:|latest_revision:smallint unsigned:NO:NULL:|latest_event:tinyint unsigned:NO:NULL:|latest_at_monotonic_usec:bigint unsigned:NO:NULL:|participant_count:smallint unsigned:NO:NULL:|expected_credit_count:smallint unsigned:NO:NULL:|source_events:bigint unsigned:NO:NULL:|quality_flags:int unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_encounter columns differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_encounter' GROUP BY index_name,non_unique,index_type ORDER BY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,encounter_boot_id:0,encounter_process_id:0,encounter_seq:0' ]] || { echo 'telemetry_rollup_encounter indexes differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT engine FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_encounter';")
[[ "$engine" == InnoDB ]] || { echo 'telemetry_rollup_encounter engine differs' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_encounter' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_observation_3_anchor|chk_observation_3_closure|chk_observation_3_evidence|chk_observation_3_identity|chk_observation_3_quality|chk_observation_3_scope|chk_observation_3_source|fk_observation_3_state' ]] || { echo 'telemetry_rollup_encounter constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),''))) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_encounter' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_observation_3_anchor:latest_at_monotonic_usec>=start_monotonic_usec|chk_observation_3_closure:close_seen=0andend_monotonic_usecisnullandend_utc_usecisnullandelapsed_usecisnullandoutcome=0orclose_seen=1andend_monotonic_usecisnotnullandelapsed_usecisnotnullandend_monotonic_usec>=start_monotonic_usecandelapsed_usec=end_monotonic_usec-start_monotonic_usecandoutcomebetween1and10|chk_observation_3_evidence:start_seenbetween0and1andclose_seenbetween0and1|chk_observation_3_identity:encounter_boot_id<>0andencounter_process_id<>0andencounter_seq<>0|chk_observation_3_quality:quality_flags&536806399=quality_flags|chk_observation_3_scope:definition_version=2andgeneration<>0andenvironment_id<>0andseason_id<>0andinput_watermark<>0|chk_observation_3_source:config_id<>0andclassifier_version<>0andpolicy_version<>0andzone_vnum>=-1andmodebetween0and3andmode_maskbetween1and15andlatest_revision>0andlatest_eventbetween1and5andsource_events>0' ]] || { echo 'telemetry_rollup_encounter checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_encounter' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_observation_3_state:1:definition_version:telemetry_rollup_state:definition_version:RESTRICT:RESTRICT:1|fk_observation_3_state:2:generation:telemetry_rollup_state:generation:RESTRICT:RESTRICT:1|fk_observation_3_state:3:environment_id:telemetry_rollup_state:environment_id:RESTRICT:RESTRICT:1|fk_observation_3_state:4:season_id:telemetry_rollup_state:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_encounter foreign keys differ' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_encounter_participant' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|encounter_boot_id:bigint unsigned:NO:NULL:|encounter_process_id:bigint unsigned:NO:NULL:|encounter_seq:bigint unsigned:NO:NULL:|subject_id:bigint unsigned:NO:NULL:|pid:int:NO:NULL:|latest_revision:smallint unsigned:NO:NULL:|latest_event:tinyint unsigned:NO:NULL:|latest_at_monotonic_usec:bigint unsigned:NO:NULL:|effort_revision:smallint unsigned:NO:NULL:|participant_usec:bigint unsigned:YES:NULL:|join_seen:tinyint unsigned:NO:NULL:|leave_seen:tinyint unsigned:NO:NULL:|summary_seen:tinyint unsigned:NO:NULL:|outcome:tinyint unsigned:NO:NULL:|quality_flags:int unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_encounter_participant columns differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_encounter_participant' GROUP BY index_name,non_unique,index_type ORDER BY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,encounter_boot_id:0,encounter_process_id:0,encounter_seq:0,subject_id:0,pid:0' ]] || { echo 'telemetry_rollup_encounter_participant indexes differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT engine FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_encounter_participant';")
[[ "$engine" == InnoDB ]] || { echo 'telemetry_rollup_encounter_participant engine differs' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_encounter_participant' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_observation_4_effort|chk_observation_4_event|chk_observation_4_evidence|chk_observation_4_identity|chk_observation_4_quality|chk_observation_4_scope|fk_observation_4_state' ]] || { echo 'telemetry_rollup_encounter_participant constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),''))) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_encounter_participant' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_observation_4_effort:effort_revision=0andparticipant_usecisnullandoutcome=0oreffort_revision>0andparticipant_usecisnotnullandoutcomebetween1and10|chk_observation_4_event:latest_revision>0andlatest_eventin2,3,5andeffort_revision<=latest_revision|chk_observation_4_evidence:join_seenbetween0and1andleave_seenbetween0and1andsummary_seenbetween0and1|chk_observation_4_identity:encounter_boot_id<>0andencounter_process_id<>0andencounter_seq<>0andsubject_id<>0andpid>0|chk_observation_4_quality:quality_flags&536806399=quality_flags|chk_observation_4_scope:definition_version=2andgeneration<>0andenvironment_id<>0andseason_id<>0andinput_watermark<>0' ]] || { echo 'telemetry_rollup_encounter_participant checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_encounter_participant' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_observation_4_state:1:definition_version:telemetry_rollup_state:definition_version:RESTRICT:RESTRICT:1|fk_observation_4_state:2:generation:telemetry_rollup_state:generation:RESTRICT:RESTRICT:1|fk_observation_4_state:3:environment_id:telemetry_rollup_state:environment_id:RESTRICT:RESTRICT:1|fk_observation_4_state:4:season_id:telemetry_rollup_state:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_encounter_participant foreign keys differ' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_combat_actor' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|encounter_boot_id:bigint unsigned:NO:NULL:|encounter_process_id:bigint unsigned:NO:NULL:|encounter_seq:bigint unsigned:NO:NULL:|actor_kind:tinyint unsigned:NO:NULL:|actor_id:bigint unsigned:NO:NULL:|config_id:bigint unsigned:NO:NULL:|classifier_version:int unsigned:NO:NULL:|policy_version:int unsigned:NO:NULL:|zone_vnum:int:NO:NULL:|group_key:bigint unsigned:NO:NULL:|actor_pid:int:NO:NULL:|owner_subject_id:bigint unsigned:NO:NULL:|revision:smallint unsigned:NO:NULL:|mode:tinyint unsigned:NO:NULL:|outcome:tinyint unsigned:NO:NULL:|start_monotonic_usec:bigint unsigned:NO:NULL:|end_monotonic_usec:bigint unsigned:NO:NULL:|start_utc_usec:bigint:YES:NULL:|end_utc_usec:bigint:YES:NULL:|unique_player_count:smallint unsigned:NO:NULL:|participant_count:smallint unsigned:NO:NULL:|dropped_participant_count:smallint unsigned:NO:NULL:|power_band:smallint unsigned:NO:NULL:|opponent_power_band:smallint unsigned:NO:NULL:|opponent_count:smallint unsigned:NO:NULL:|modifier_flags:int unsigned:NO:NULL:|damage_dealt:bigint unsigned:NO:NULL:|damage_taken:bigint unsigned:NO:NULL:|healing_attempted:bigint unsigned:NO:NULL:|effective_healing:bigint unsigned:NO:NULL:|overhealing:bigint unsigned:NO:NULL:|control_applications:bigint unsigned:NO:NULL:|casting_attempts:bigint unsigned:NO:NULL:|casting_completions:bigint unsigned:NO:NULL:|casting_aborts:bigint unsigned:NO:NULL:|casting_elapsed_usec:bigint unsigned:NO:NULL:|tanking_usec:bigint unsigned:NO:NULL:|quality_flags:int unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_combat_actor columns differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_combat_actor' GROUP BY index_name,non_unique,index_type ORDER BY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,encounter_boot_id:0,encounter_process_id:0,encounter_seq:0,actor_kind:0,actor_id:0' ]] || { echo 'telemetry_rollup_combat_actor indexes differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT engine FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_combat_actor';")
[[ "$engine" == InnoDB ]] || { echo 'telemetry_rollup_combat_actor engine differs' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_combat_actor' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_observation_5_casting|chk_observation_5_counts|chk_observation_5_healing|chk_observation_5_identity|chk_observation_5_owner|chk_observation_5_quality|chk_observation_5_scope|chk_observation_5_source|chk_observation_5_window|fk_observation_5_state' ]] || { echo 'telemetry_rollup_combat_actor constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),''))) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_combat_actor' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_observation_5_casting:casting_completions<=casting_attemptsandcasting_aborts<=casting_attempts-casting_completions|chk_observation_5_counts:unique_player_count<=64andparticipant_count<=64|chk_observation_5_healing:effective_healing<=healing_attempted|chk_observation_5_identity:encounter_boot_id<>0andencounter_process_id<>0andencounter_seq<>0andactor_id<>0|chk_observation_5_owner:actor_kind=1andactor_pid>0andowner_subject_id=actor_idoractor_kind=2andactor_pid=-1andowner_subject_id<>0oractor_kind=3andactor_pid=-1andowner_subject_id=0|chk_observation_5_quality:quality_flags&536806399=quality_flags|chk_observation_5_scope:definition_version=2andgeneration<>0andenvironment_id<>0andseason_id<>0andinput_watermark<>0|chk_observation_5_source:config_id<>0andclassifier_version<>0andpolicy_version<>0andzone_vnum>=-1andrevision>0andmodebetween1and3andoutcomebetween1and10andmodifier_flags<=255|chk_observation_5_window:end_monotonic_usec>=start_monotonic_usec' ]] || { echo 'telemetry_rollup_combat_actor checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_combat_actor' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_observation_5_state:1:definition_version:telemetry_rollup_state:definition_version:RESTRICT:RESTRICT:1|fk_observation_5_state:2:generation:telemetry_rollup_state:generation:RESTRICT:RESTRICT:1|fk_observation_5_state:3:environment_id:telemetry_rollup_state:environment_id:RESTRICT:RESTRICT:1|fk_observation_5_state:4:season_id:telemetry_rollup_state:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_combat_actor foreign keys differ' >&2; exit 1; }
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
    unenforced=$("${MYSQL[@]}" -e "SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND constraint_type='CHECK' AND table_name IN ('telemetry_rollup_progression_day','telemetry_rollup_level_event','telemetry_rollup_encounter','telemetry_rollup_encounter_participant','telemetry_rollup_combat_actor') AND enforced <> 'YES';")
    [[ "$unenforced" == 0 ]] || { echo 'telemetry observation checks are not enforced' >&2; exit 1; }
fi
printf 'telemetry observation projection schema verified\n'
