#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_identity_reviewer' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|database_principal:varchar(384):NO:NULL:|reviewer_token:binary(32):NO:NULL:|enabled:tinyint unsigned:NO:NULL:' ]] || { echo 'telemetry_identity_reviewer shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_identity_reviewer' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == PRIMARY:0:BTREE:environment_id:0,season_id:0,database_principal:0 ]] || { echo 'telemetry_identity_reviewer indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_identity_reviewer' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_identity_reviewer_authority|chk_identity_reviewer_scope' ]] || { echo 'telemetry_identity_reviewer constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_identity_reviewer' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_identity_reviewer_authority:enabledin0,1andreviewer_token<>repeatchar0,32|chk_identity_reviewer_scope:environment_id<>0andseason_id<>0andlengthdatabase_principal>0' ]] || { echo 'telemetry_identity_reviewer checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_identity_reviewer' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == '' ]] || { echo 'telemetry_identity_reviewer foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_identity_reviewer';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_identity_reviewer engine or collation differs' >&2; exit 1; }
collation=$("${MYSQL[@]}" -e "SELECT collation_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_identity_reviewer' AND column_name='database_principal';")
[[ "$collation" == utf8mb4_bin ]] || { echo 'telemetry_identity_reviewer principal collation differs' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_identity_registry' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|registry_version:bigint unsigned:NO:NULL:|previous_registry_version:bigint unsigned:NO:NULL:|previous_packet_digest:binary(32):YES:NULL:|reviewed_from_utc_usec:bigint:NO:NULL:|reviewed_through_utc_usec:bigint:NO:NULL:|reviewed_at_utc_usec:bigint:NO:NULL:|reviewer_token:binary(32):NO:NULL:|review_evidence_digest:binary(32):NO:NULL:|packet_digest:binary(32):NO:NULL:|association_count:smallint unsigned:NO:NULL:|database_principal:varchar(384):NO:NULL:|registered_at_utc_usec:bigint:NO:NULL:' ]] || { echo 'telemetry_identity_registry shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_identity_registry' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:environment_id:0,season_id:0,registry_version:0|uq_identity_registry_digest:0:BTREE:environment_id:0,season_id:0,registry_version:0,packet_digest:0' ]] || { echo 'telemetry_identity_registry indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_identity_registry' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_identity_registry_evidence|chk_identity_registry_previous|chk_identity_registry_scope|chk_identity_registry_time|uq_identity_registry_digest' ]] || { echo 'telemetry_identity_registry constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_identity_registry' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_identity_registry_evidence:association_count<=1024andreviewer_token<>repeatchar0,32andreview_evidence_digest<>repeatchar0,32andpacket_digest<>repeatchar0,32|chk_identity_registry_previous:previous_registry_version=0andprevious_packet_digestisnullorprevious_registry_version>0andprevious_packet_digestisnotnullandprevious_packet_digest<>repeatchar0,32|chk_identity_registry_scope:environment_id<>0andseason_id<>0andregistry_version>previous_registry_versionandregistry_version-previous_registry_version=1andlengthdatabase_principal>0|chk_identity_registry_time:castreviewed_from_utc_usecasunsigned<>9223372036854775808andreviewed_from_utc_usec<reviewed_through_utc_usecandreviewed_through_utc_usec<=reviewed_at_utc_usecandreviewed_at_utc_usec<=registered_at_utc_usec' ]] || { echo 'telemetry_identity_registry checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_identity_registry' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == '' ]] || { echo 'telemetry_identity_registry foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_identity_registry';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_identity_registry engine or collation differs' >&2; exit 1; }
collation=$("${MYSQL[@]}" -e "SELECT collation_name FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_identity_registry' AND column_name='database_principal';")
[[ "$collation" == utf8mb4_bin ]] || { echo 'telemetry_identity_registry principal collation differs' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_identity_association' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|registry_version:bigint unsigned:NO:NULL:|association_id:bigint unsigned:NO:NULL:|account_token:bigint unsigned:NO:NULL:|controller_token:bigint unsigned:YES:NULL:|valid_from_utc_usec:bigint:NO:NULL:|valid_through_utc_usec:bigint:YES:NULL:|status:tinyint unsigned:NO:NULL:|provenance:tinyint unsigned:NO:NULL:|evidence_digest:binary(32):NO:NULL:' ]] || { echo 'telemetry_identity_association shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_identity_association' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:environment_id:0,season_id:0,registry_version:0,association_id:0|idx_identity_association_account:1:BTREE:environment_id:0,season_id:0,account_token:0' ]] || { echo 'telemetry_identity_association indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_identity_association' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_identity_association_evidence|chk_identity_association_identity|chk_identity_association_status|chk_identity_association_time|fk_identity_association_account|fk_identity_association_registry' ]] || { echo 'telemetry_identity_association constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_identity_association' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_identity_association_evidence:provenancebetween1and3andevidence_digest<>repeatchar0,32|chk_identity_association_identity:association_id<>0andaccount_token<>0andcontroller_tokenisnullorcontroller_token<>0|chk_identity_association_status:status=1andcontroller_tokenisnotnullorstatus=2andcontroller_tokenisnullorstatus=3|chk_identity_association_time:castvalid_from_utc_usecasunsigned<>9223372036854775808andvalid_through_utc_usecisnullorvalid_through_utc_usec>valid_from_utc_usec' ]] || { echo 'telemetry_identity_association checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_identity_association' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_identity_association_account:1:environment_id:telemetry_account_token:environment_id:RESTRICT:RESTRICT:1|fk_identity_association_account:2:season_id:telemetry_account_token:season_id:RESTRICT:RESTRICT:1|fk_identity_association_account:3:account_token:telemetry_account_token:account_token:RESTRICT:RESTRICT:1|fk_identity_association_registry:1:environment_id:telemetry_identity_registry:environment_id:RESTRICT:RESTRICT:1|fk_identity_association_registry:2:season_id:telemetry_identity_registry:season_id:RESTRICT:RESTRICT:1|fk_identity_association_registry:3:registry_version:telemetry_identity_registry:registry_version:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_identity_association foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_identity_association';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_identity_association engine or collation differs' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_generation_identity' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|registry_version:bigint unsigned:YES:NULL:|registry_digest:binary(32):YES:NULL:|reviewed_from_utc_usec:bigint:YES:NULL:|reviewed_through_utc_usec:bigint:YES:NULL:|reviewed_at_utc_usec:bigint:YES:NULL:|association_count:smallint unsigned:NO:NULL:' ]] || { echo 'telemetry_generation_identity shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_generation_identity' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0|idx_generation_identity_registry:1:BTREE:environment_id:0,season_id:0,registry_version:0,registry_digest:0' ]] || { echo 'telemetry_generation_identity indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_generation_identity' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_generation_identity_review|chk_generation_identity_scope|fk_generation_identity_registry' ]] || { echo 'telemetry_generation_identity constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_generation_identity' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_generation_identity_review:registry_versionisnullandregistry_digestisnullandreviewed_from_utc_usecisnullandreviewed_through_utc_usecisnullandreviewed_at_utc_usecisnullandassociation_count=0orregistry_versionisnotnullandregistry_version>0andregistry_digestisnotnullandregistry_digest<>repeatchar0,32andreviewed_from_utc_usecisnotnullandcastreviewed_from_utc_usecasunsigned<>9223372036854775808andreviewed_through_utc_usecisnotnullandreviewed_at_utc_usecisnotnullandreviewed_from_utc_usec<reviewed_through_utc_usecandreviewed_through_utc_usec<=reviewed_at_utc_usecandassociation_count<=1024|chk_generation_identity_scope:definition_version>=3andgeneration<>0andenvironment_id<>0andseason_id<>0' ]] || { echo 'telemetry_generation_identity checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_generation_identity' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_generation_identity_registry:1:environment_id:telemetry_identity_registry:environment_id:RESTRICT:RESTRICT:1|fk_generation_identity_registry:2:season_id:telemetry_identity_registry:season_id:RESTRICT:RESTRICT:1|fk_generation_identity_registry:3:registry_version:telemetry_identity_registry:registry_version:RESTRICT:RESTRICT:1|fk_generation_identity_registry:4:registry_digest:telemetry_identity_registry:packet_digest:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_generation_identity foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_generation_identity';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_generation_identity engine or collation differs' >&2; exit 1; }
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
    unenforced=$("${MYSQL[@]}" -e "SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND constraint_type='CHECK' AND table_name IN ('telemetry_identity_reviewer','telemetry_identity_registry','telemetry_identity_association','telemetry_generation_identity') AND enforced <> 'YES';")
    [[ "$unenforced" == 0 ]] || { echo 'telemetry identity review checks are not enforced' >&2; exit 1; }
fi
printf 'telemetry identity review schema verified\n'
