#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_incident_registry_v2' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|registry_version:bigint unsigned:NO:NULL:|previous_registry_version:bigint unsigned:NO:NULL:|reviewed_from_utc_usec:bigint:YES:NULL:|reviewed_through_utc_usec:bigint:YES:NULL:|reviewer_token:binary(32):NO:NULL:|review_evidence_digest:binary(32):NO:NULL:|packet_digest:binary(32):NO:NULL:|incident_count:smallint unsigned:NO:NULL:' ]] || { echo 'telemetry_incident_registry_v2 shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_incident_registry_v2' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == PRIMARY:0:BTREE:environment_id:0,season_id:0,registry_version:0 ]] || { echo 'telemetry_incident_registry_v2 indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_incident_registry_v2' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_incident_registry_count_v2|chk_incident_registry_time_v2|chk_incident_registry_utc_v2|chk_incident_registry_version_v2' ]] || { echo 'telemetry_incident_registry_v2 constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_incident_registry_v2' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_incident_registry_count_v2:incident_count<=64|chk_incident_registry_time_v2:reviewed_from_utc_usecisnullorreviewed_through_utc_usecisnullorreviewed_from_utc_usec<=reviewed_through_utc_usec|chk_incident_registry_utc_v2:reviewed_from_utc_usecisnullorcastreviewed_from_utc_usecasunsigned<>9223372036854775808andreviewed_through_utc_usecisnullorcastreviewed_through_utc_usecasunsigned<>9223372036854775808|chk_incident_registry_version_v2:environment_id<>0andseason_id<>0andregistry_version<>0andprevious_registry_version<registry_versionandregistry_version-previous_registry_version=1' ]] || { echo 'telemetry_incident_registry_v2 checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_incident_registry_v2' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == '' ]] || { echo 'telemetry_incident_registry_v2 foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_incident_registry_v2';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_incident_registry_v2 engine or collation differs' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_incident_v2' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|registry_version:bigint unsigned:NO:NULL:|incident_id:bigint unsigned:NO:NULL:|producer_boot_id:bigint unsigned:YES:NULL:|producer_process_id:bigint unsigned:YES:NULL:|start_utc_usec:bigint:YES:NULL:|end_utc_usec:bigint:YES:NULL:|record_kind_mask:bigint unsigned:NO:NULL:|first_record_seq:bigint unsigned:YES:NULL:|last_record_seq:bigint unsigned:YES:NULL:|fix_reference_digest:binary(32):YES:NULL:|verified_boot_id:bigint unsigned:YES:NULL:|verified_process_id:bigint unsigned:YES:NULL:|verified_record_seq:bigint unsigned:YES:NULL:|verified_record_kind:tinyint unsigned:YES:NULL:|verified_occurrence_utc_usec:bigint:YES:NULL:|backlog_disposition:tinyint unsigned:NO:NULL:|observation_provenance:tinyint unsigned:NO:NULL:|evidence_digest:binary(32):NO:NULL:|status:tinyint unsigned:NO:NULL:' ]] || { echo 'telemetry_incident_v2 shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_incident_v2' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == PRIMARY:0:BTREE:environment_id:0,season_id:0,registry_version:0,incident_id:0 ]] || { echo 'telemetry_incident_v2 indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_incident_v2' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_incident_disposition_v2|chk_incident_family_v2|chk_incident_identity_v2|chk_incident_sequence_v2|chk_incident_time_v2|chk_incident_utc_v2|chk_incident_verification_v2|fk_incident_registry_v2' ]] || { echo 'telemetry_incident_v2 constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_incident_v2' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_incident_disposition_v2:backlog_dispositionbetween0and5andobservation_provenancebetween1and3andstatusbetween1and2|chk_incident_family_v2:record_kind_maskbetween2and1022andrecord_kind_mask&1=0|chk_incident_identity_v2:incident_id<>0andproducer_boot_idisnullandproducer_process_idisnullandfirst_record_seqisnullandlast_record_seqisnullorproducer_boot_idisnotnullandproducer_process_idisnotnullandproducer_boot_id>0andproducer_process_id>0|chk_incident_sequence_v2:first_record_seqisnullorfirst_record_seq>0andlast_record_seqisnullorlast_record_seq>0andfirst_record_seqisnullorlast_record_seqisnullorfirst_record_seq<=last_record_seq|chk_incident_time_v2:start_utc_usecisnullorend_utc_usecisnullorstart_utc_usec<=end_utc_usec|chk_incident_utc_v2:start_utc_usecisnullorcaststart_utc_usecasunsigned<>9223372036854775808andend_utc_usecisnullorcastend_utc_usecasunsigned<>9223372036854775808andverified_occurrence_utc_usecisnullorcastverified_occurrence_utc_usecasunsigned<>9223372036854775808|chk_incident_verification_v2:verified_boot_idisnullandverified_process_idisnullandverified_record_seqisnullandverified_record_kindisnullandverified_occurrence_utc_usecisnullorfix_reference_digestisnotnullandverified_boot_idisnotnullandverified_process_idisnotnullandverified_record_seqisnotnullandverified_record_kindisnotnullandverified_boot_id>0andverified_process_id>0andverified_record_seq>0andverified_record_kindbetween1and9andrecord_kind_mask&1<<verified_record_kind<>0' ]] || { echo 'telemetry_incident_v2 checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_incident_v2' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_incident_registry_v2:1:environment_id:telemetry_incident_registry_v2:environment_id:RESTRICT:RESTRICT:1|fk_incident_registry_v2:2:season_id:telemetry_incident_registry_v2:season_id:RESTRICT:RESTRICT:1|fk_incident_registry_v2:3:registry_version:telemetry_incident_registry_v2:registry_version:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_incident_v2 foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_incident_v2';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_incident_v2 engine or collation differs' >&2; exit 1; }
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
    unenforced=$("${MYSQL[@]}" -e "SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND constraint_type='CHECK' AND table_name IN ('telemetry_incident_registry_v2','telemetry_incident_v2') AND enforced <> 'YES';")
    [[ "$unenforced" == 0 ]] || { echo 'telemetry ownership incident checks are not enforced' >&2; exit 1; }
fi
printf 'telemetry ownership incident schema verified\n'
