#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_identity_coverage' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:|source_fact_count:int unsigned:NO:NULL:|source_digest:binary(32):NO:NULL:|publication_complete:tinyint unsigned:NO:NULL:|interval_count:int unsigned:NO:NULL:|ownership_count:int unsigned:NO:NULL:|progression_count:int unsigned:NO:NULL:|effort_row_count:int unsigned:NO:NULL:|portfolio_row_count:int unsigned:NO:NULL:|effort_slice_count:int unsigned:NO:NULL:|observed_character_usec:bigint unsigned:NO:NULL:|owned_character_usec:bigint unsigned:NO:NULL:|confirmed_controller_character_usec:bigint unsigned:NO:NULL:|unknown_account_character_usec:bigint unsigned:NO:NULL:|unlinked_controller_character_usec:bigint unsigned:NO:NULL:|incident_affected_character_usec:bigint unsigned:NO:NULL:|quality_flags:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_identity_coverage shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_identity_coverage' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0 ]] || { echo 'telemetry_rollup_identity_coverage indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_identity_coverage' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_identity_coverage_bounds|chk_identity_coverage_complete|chk_identity_coverage_quality|chk_identity_coverage_scope|fk_identity_coverage_reservation|fk_identity_coverage_state' ]] || { echo 'telemetry_rollup_identity_coverage constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_identity_coverage' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_identity_coverage_bounds:source_fact_count<=16384andeffort_slice_count<=16384andeffort_row_count<=100000andportfolio_row_count<=100000|chk_identity_coverage_complete:publication_completebetween0and1andpublication_complete=0orsource_fact_count=interval_count+ownership_count+progression_countandobserved_character_usec=owned_character_usec+unknown_account_character_usecandobserved_character_usec=confirmed_controller_character_usec+unlinked_controller_character_usecandincident_affected_character_usec<=observed_character_usec|chk_identity_coverage_quality:quality_flags&18446744073172745216=0|chk_identity_coverage_scope:definition_version=3andgeneration<>0andenvironment_id<>0andseason_id<>0' ]] || { echo 'telemetry_rollup_identity_coverage checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_identity_coverage' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_identity_coverage_reservation:1:definition_version:telemetry_generation_identity:definition_version:RESTRICT:RESTRICT:1|fk_identity_coverage_reservation:2:generation:telemetry_generation_identity:generation:RESTRICT:RESTRICT:1|fk_identity_coverage_reservation:3:environment_id:telemetry_generation_identity:environment_id:RESTRICT:RESTRICT:1|fk_identity_coverage_reservation:4:season_id:telemetry_generation_identity:season_id:RESTRICT:RESTRICT:1|fk_identity_coverage_state:1:definition_version:telemetry_rollup_state:definition_version:RESTRICT:RESTRICT:1|fk_identity_coverage_state:2:generation:telemetry_rollup_state:generation:RESTRICT:RESTRICT:1|fk_identity_coverage_state:3:environment_id:telemetry_rollup_state:environment_id:RESTRICT:RESTRICT:1|fk_identity_coverage_state:4:season_id:telemetry_rollup_state:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_identity_coverage foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_identity_coverage';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_rollup_identity_coverage engine or collation differs' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_identity_input' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|ingest_id:bigint unsigned:NO:NULL:|boot_id:bigint unsigned:NO:NULL:|process_id:bigint unsigned:NO:NULL:|record_seq:bigint unsigned:NO:NULL:|subject_id:bigint unsigned:NO:NULL:|pid:int:NO:NULL:|record_kind:tinyint unsigned:NO:NULL:|payload:varbinary(4096):NO:NULL:|payload_digest:binary(32):NO:NULL:' ]] || { echo 'telemetry_identity_input shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_identity_input' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,ingest_id:0|uq_identity_input_replay:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,boot_id:0,process_id:0,record_seq:0' ]] || { echo 'telemetry_identity_input indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_identity_input' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_identity_input_identity|chk_identity_input_kind|chk_identity_input_payload|chk_identity_input_scope|fk_identity_input_coverage|uq_identity_input_replay' ]] || { echo 'telemetry_identity_input constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_identity_input' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_identity_input_identity:ingest_id>0andboot_id>0andprocess_id>0andrecord_seq>0andsubject_id>0andpid>0|chk_identity_input_kind:record_kindin1,6,9|chk_identity_input_payload:lengthpayloadbetween1and4096|chk_identity_input_scope:definition_version=3andgeneration<>0andenvironment_id<>0andseason_id<>0' ]] || { echo 'telemetry_identity_input checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_identity_input' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_identity_input_coverage:1:definition_version:telemetry_rollup_identity_coverage:definition_version:RESTRICT:RESTRICT:1|fk_identity_input_coverage:2:generation:telemetry_rollup_identity_coverage:generation:RESTRICT:RESTRICT:1|fk_identity_input_coverage:3:environment_id:telemetry_rollup_identity_coverage:environment_id:RESTRICT:RESTRICT:1|fk_identity_input_coverage:4:season_id:telemetry_rollup_identity_coverage:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_identity_input foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_identity_input';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_identity_input engine or collation differs' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_identity_effort' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|cell_digest:binary(32):NO:NULL:|utc_day:date:NO:NULL:|partition_kind:tinyint unsigned:NO:NULL:|basis:tinyint unsigned:NO:NULL:|identity_token:bigint unsigned:NO:NULL:|config_id:bigint unsigned:NO:NULL:|classifier_version:int unsigned:NO:NULL:|policy_version:int unsigned:NO:NULL:|faction_id:smallint unsigned:NO:NULL:|level_band:smallint unsigned:NO:NULL:|group_context_mode:tinyint unsigned:NO:NULL:|category:tinyint unsigned:NO:NULL:|character_usec:bigint unsigned:NO:NULL:|utc_covered_character_usec:bigint unsigned:NO:NULL:|unknown_clock_character_usec:bigint unsigned:NO:NULL:|covered_union_usec:bigint unsigned:YES:NULL:|union_usec:bigint unsigned:YES:NULL:|distinct_characters:int unsigned:NO:NULL:|distinct_accounts:int unsigned:NO:NULL:|quality_flags:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_identity_effort shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_identity_effort' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,cell_digest:0 ]] || { echo 'telemetry_rollup_identity_effort indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_identity_effort' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_identity_effort_basis|chk_identity_effort_context|chk_identity_effort_counters|chk_identity_effort_quality|chk_identity_effort_scope|chk_identity_effort_union|fk_identity_effort_coverage' ]] || { echo 'telemetry_rollup_identity_effort constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_identity_effort' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_identity_effort_basis:basisbetween1and3andidentity_token>0orbasisin4,5andidentity_token=0|chk_identity_effort_context:config_id>0andclassifier_version>0andpolicy_version>0andgroup_context_modebetween0and2andpartition_kindbetween0and1andpartition_kind<>0orfaction_id=0andlevel_band=0andgroup_context_mode=0|chk_identity_effort_counters:categorybetween0and4andcharacter_usec=utc_covered_character_usec+unknown_clock_character_usecandcovered_union_usecisnullorcovered_union_usec<=utc_covered_character_usec|chk_identity_effort_quality:quality_flags&18446744073172745216=0|chk_identity_effort_scope:definition_version=3andgeneration<>0andenvironment_id<>0andseason_id<>0|chk_identity_effort_union:basisin4,5andcovered_union_usecisnullandunion_usecisnullorbasisbetween1and3andcovered_union_usecisnotnullandunion_usecisnullorunknown_clock_character_usec=0andunion_usec=covered_union_usec' ]] || { echo 'telemetry_rollup_identity_effort checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_identity_effort' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_identity_effort_coverage:1:definition_version:telemetry_rollup_identity_coverage:definition_version:RESTRICT:RESTRICT:1|fk_identity_effort_coverage:2:generation:telemetry_rollup_identity_coverage:generation:RESTRICT:RESTRICT:1|fk_identity_effort_coverage:3:environment_id:telemetry_rollup_identity_coverage:environment_id:RESTRICT:RESTRICT:1|fk_identity_effort_coverage:4:season_id:telemetry_rollup_identity_coverage:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_identity_effort foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_identity_effort';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_rollup_identity_effort engine or collation differs' >&2; exit 1; }
shape=$("${MYSQL[@]}" -e "SELECT CONCAT(column_name,':',CASE WHEN data_type IN ('int','bigint','smallint','tinyint') THEN CONCAT(data_type,IF(column_type LIKE '%unsigned%',' unsigned','')) ELSE column_type END,':',is_nullable,':',COALESCE(column_default,'NULL'),':',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_portfolio_xp' ORDER BY ordinal_position;" | paste -sd'|' -)
[[ "$shape" == 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|cell_digest:binary(32):NO:NULL:|utc_day:date:NO:NULL:|partition_kind:tinyint unsigned:NO:NULL:|basis:tinyint unsigned:NO:NULL:|identity_token:bigint unsigned:NO:NULL:|config_id:bigint unsigned:NO:NULL:|classifier_version:int unsigned:NO:NULL:|policy_version:int unsigned:NO:NULL:|faction_id:smallint unsigned:NO:NULL:|level_band:smallint unsigned:NO:NULL:|group_context_mode:tinyint unsigned:NO:NULL:|source:tinyint unsigned:NO:NULL:|reason:tinyint unsigned:NO:NULL:|observation_status:tinyint unsigned:NO:NULL:|modifier_flags:smallint unsigned:NO:NULL:|observations:bigint unsigned:NO:NULL:|zero_applied_observations:bigint unsigned:NO:NULL:|negative_applied_observations:bigint unsigned:NO:NULL:|requested_xp:bigint:NO:NULL:|computed_xp:bigint:NO:NULL:|applied_xp:bigint:NO:NULL:|earned_positive_xp:bigint unsigned:NO:NULL:|death_loss_xp:bigint unsigned:NO:NULL:|restored_positive_xp:bigint unsigned:NO:NULL:|linked_observations:bigint unsigned:NO:NULL:|clock_unknown_observations:bigint unsigned:NO:NULL:|incident_affected_observations:bigint unsigned:NO:NULL:|quality_flags:bigint unsigned:NO:NULL:' ]] || { echo 'telemetry_rollup_portfolio_xp shape differ' >&2; exit 1; }
indexes=$("${MYSQL[@]}" -e "SELECT CONCAT(index_name,':',non_unique,':',index_type,':',GROUP_CONCAT(CONCAT(column_name,':',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR ',')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_portfolio_xp' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;" | paste -sd'|' -)
[[ "$indexes" == PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,cell_digest:0 ]] || { echo 'telemetry_rollup_portfolio_xp indexes differ' >&2; exit 1; }
constraints=$("${MYSQL[@]}" -e "SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='telemetry_rollup_portfolio_xp' ORDER BY BINARY constraint_name;" | paste -sd'|' -)
[[ "$constraints" == 'PRIMARY|chk_identity_portfolio_xp_basis|chk_identity_portfolio_xp_context|chk_identity_portfolio_xp_counts|chk_identity_portfolio_xp_quality|chk_identity_portfolio_xp_scope|chk_identity_portfolio_xp_source|fk_identity_portfolio_xp_coverage' ]] || { echo 'telemetry_rollup_portfolio_xp constraints differ' >&2; exit 1; }
checks=$("${MYSQL[@]}" -e "SELECT CONCAT(t.constraint_name,':',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,' ',''),CHAR(96),''),'(',''),')',''),CHAR(10),'')),'octet_length','length')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='telemetry_rollup_portfolio_xp' AND t.constraint_type='CHECK' ORDER BY BINARY t.constraint_name;" | paste -sd'|' -)
[[ "$checks" == 'chk_identity_portfolio_xp_basis:basisbetween1and3andidentity_token>0orbasisin4,5andidentity_token=0|chk_identity_portfolio_xp_context:config_id>0andclassifier_version>0andpolicy_version>0andgroup_context_modebetween0and2andpartition_kindbetween0and1andpartition_kind<>0orfaction_id=0andlevel_band=0andgroup_context_mode=0|chk_identity_portfolio_xp_counts:zero_applied_observations+negative_applied_observations<=observationsandlinked_observations<=observationsandclock_unknown_observations<=observationsandincident_affected_observations<=observations|chk_identity_portfolio_xp_quality:quality_flags&18446744073172745216=0|chk_identity_portfolio_xp_scope:definition_version=3andgeneration<>0andenvironment_id<>0andseason_id<>0|chk_identity_portfolio_xp_source:sourcebetween0and12andreasonbetween0and6andobservation_statusbetween1and3andmodifier_flags<=511' ]] || { echo 'telemetry_rollup_portfolio_xp checks differ' >&2; exit 1; }
foreign=$("${MYSQL[@]}" -e "SELECT CONCAT(k.constraint_name,':',k.ordinal_position,':',k.column_name,':',k.referenced_table_name,':',k.referenced_column_name,':',r.update_rule,':',r.delete_rule,':',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='telemetry_rollup_portfolio_xp' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;" | paste -sd'|' -)
[[ "$foreign" == 'fk_identity_portfolio_xp_coverage:1:definition_version:telemetry_rollup_identity_coverage:definition_version:RESTRICT:RESTRICT:1|fk_identity_portfolio_xp_coverage:2:generation:telemetry_rollup_identity_coverage:generation:RESTRICT:RESTRICT:1|fk_identity_portfolio_xp_coverage:3:environment_id:telemetry_rollup_identity_coverage:environment_id:RESTRICT:RESTRICT:1|fk_identity_portfolio_xp_coverage:4:season_id:telemetry_rollup_identity_coverage:season_id:RESTRICT:RESTRICT:1' ]] || { echo 'telemetry_rollup_portfolio_xp foreign differ' >&2; exit 1; }
engine=$("${MYSQL[@]}" -e "SELECT CONCAT(engine,':',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='telemetry_rollup_portfolio_xp';")
[[ "$engine" == InnoDB:utf8mb4_unicode_ci ]] || { echo 'telemetry_rollup_portfolio_xp engine or collation differs' >&2; exit 1; }
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
    unenforced=$("${MYSQL[@]}" -e "SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND constraint_type='CHECK' AND table_name IN ('telemetry_rollup_identity_coverage','telemetry_identity_input','telemetry_rollup_identity_effort','telemetry_rollup_portfolio_xp') AND enforced <> 'YES';")
    [[ "$unenforced" == 0 ]] || { echo 'identity publication checks are not enforced' >&2; exit 1; }
fi
printf 'identity publication schema verified\n'
