-- Retained cursor inputs and atomic reviewed identity effort/XP publication.
-- Definition 1/2 tables, contracts and sealed histories are unchanged.

CREATE TABLE IF NOT EXISTS telemetry_rollup_identity_coverage (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    input_watermark BIGINT UNSIGNED NOT NULL,
    source_fact_count INT UNSIGNED NOT NULL,
    source_digest BINARY(32) NOT NULL,
    publication_complete TINYINT UNSIGNED NOT NULL,
    interval_count INT UNSIGNED NOT NULL,
    ownership_count INT UNSIGNED NOT NULL,
    progression_count INT UNSIGNED NOT NULL,
    effort_row_count INT UNSIGNED NOT NULL,
    portfolio_row_count INT UNSIGNED NOT NULL,
    effort_slice_count INT UNSIGNED NOT NULL,
    observed_character_usec BIGINT UNSIGNED NOT NULL,
    owned_character_usec BIGINT UNSIGNED NOT NULL,
    confirmed_controller_character_usec BIGINT UNSIGNED NOT NULL,
    unknown_account_character_usec BIGINT UNSIGNED NOT NULL,
    unlinked_controller_character_usec BIGINT UNSIGNED NOT NULL,
    incident_affected_character_usec BIGINT UNSIGNED NOT NULL,
    quality_flags BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id),
    CONSTRAINT fk_identity_coverage_reservation FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_generation_identity (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT fk_identity_coverage_state FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_state (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_identity_coverage_scope CHECK (definition_version = 3 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0),
    CONSTRAINT chk_identity_coverage_bounds CHECK (source_fact_count <= 16384 AND effort_slice_count <= 16384 AND effort_row_count <= 100000 AND portfolio_row_count <= 100000),
    CONSTRAINT chk_identity_coverage_complete CHECK (publication_complete BETWEEN 0 AND 1 AND (publication_complete = 0 OR (source_fact_count = interval_count + ownership_count + progression_count AND observed_character_usec = owned_character_usec + unknown_account_character_usec AND observed_character_usec = confirmed_controller_character_usec + unlinked_controller_character_usec AND incident_affected_character_usec <= observed_character_usec))),
    CONSTRAINT chk_identity_coverage_quality CHECK ((quality_flags & 18446744073172745216) = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_identity_input (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    ingest_id BIGINT UNSIGNED NOT NULL,
    boot_id BIGINT UNSIGNED NOT NULL,
    process_id BIGINT UNSIGNED NOT NULL,
    record_seq BIGINT UNSIGNED NOT NULL,
    subject_id BIGINT UNSIGNED NOT NULL,
    pid INT NOT NULL,
    record_kind TINYINT UNSIGNED NOT NULL,
    payload VARBINARY(4096) NOT NULL,
    payload_digest BINARY(32) NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,ingest_id),
    UNIQUE KEY uq_identity_input_replay (definition_version,generation,environment_id,season_id,boot_id,process_id,record_seq),
    CONSTRAINT fk_identity_input_coverage FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_identity_coverage (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_identity_input_scope CHECK (definition_version = 3 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0),
    CONSTRAINT chk_identity_input_identity CHECK (ingest_id > 0 AND boot_id > 0 AND process_id > 0 AND record_seq > 0 AND subject_id > 0 AND pid > 0),
    CONSTRAINT chk_identity_input_kind CHECK (record_kind IN (1,6,9)),
    CONSTRAINT chk_identity_input_payload CHECK (OCTET_LENGTH(payload) BETWEEN 1 AND 4096)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_identity_effort (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    cell_digest BINARY(32) NOT NULL,
    utc_day DATE NOT NULL,
    partition_kind TINYINT UNSIGNED NOT NULL,
    basis TINYINT UNSIGNED NOT NULL,
    identity_token BIGINT UNSIGNED NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    classifier_version INT UNSIGNED NOT NULL,
    policy_version INT UNSIGNED NOT NULL,
    faction_id SMALLINT UNSIGNED NOT NULL,
    level_band SMALLINT UNSIGNED NOT NULL,
    group_context_mode TINYINT UNSIGNED NOT NULL,
    category TINYINT UNSIGNED NOT NULL,
    character_usec BIGINT UNSIGNED NOT NULL,
    utc_covered_character_usec BIGINT UNSIGNED NOT NULL,
    unknown_clock_character_usec BIGINT UNSIGNED NOT NULL,
    covered_union_usec BIGINT UNSIGNED NULL,
    union_usec BIGINT UNSIGNED NULL,
    distinct_characters INT UNSIGNED NOT NULL,
    distinct_accounts INT UNSIGNED NOT NULL,
    quality_flags BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,cell_digest),
    CONSTRAINT fk_identity_effort_coverage FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_identity_coverage (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_identity_effort_scope CHECK (definition_version = 3 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0),
    CONSTRAINT chk_identity_effort_basis CHECK (((basis BETWEEN 1 AND 3 AND identity_token > 0) OR (basis IN (4,5) AND identity_token = 0))),
    CONSTRAINT chk_identity_effort_context CHECK (config_id > 0 AND classifier_version > 0 AND policy_version > 0 AND group_context_mode BETWEEN 0 AND 2 AND partition_kind BETWEEN 0 AND 1 AND (partition_kind <> 0 OR (faction_id = 0 AND level_band = 0 AND group_context_mode = 0))),
    CONSTRAINT chk_identity_effort_counters CHECK (category BETWEEN 0 AND 4 AND character_usec = utc_covered_character_usec + unknown_clock_character_usec AND (covered_union_usec IS NULL OR covered_union_usec <= utc_covered_character_usec)),
    CONSTRAINT chk_identity_effort_union CHECK (((basis IN (4,5) AND covered_union_usec IS NULL AND union_usec IS NULL) OR (basis BETWEEN 1 AND 3 AND covered_union_usec IS NOT NULL AND (union_usec IS NULL OR (unknown_clock_character_usec = 0 AND union_usec = covered_union_usec))))),
    CONSTRAINT chk_identity_effort_quality CHECK ((quality_flags & 18446744073172745216) = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_portfolio_xp (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    cell_digest BINARY(32) NOT NULL,
    utc_day DATE NOT NULL,
    partition_kind TINYINT UNSIGNED NOT NULL,
    basis TINYINT UNSIGNED NOT NULL,
    identity_token BIGINT UNSIGNED NOT NULL,
    config_id BIGINT UNSIGNED NOT NULL,
    classifier_version INT UNSIGNED NOT NULL,
    policy_version INT UNSIGNED NOT NULL,
    faction_id SMALLINT UNSIGNED NOT NULL,
    level_band SMALLINT UNSIGNED NOT NULL,
    group_context_mode TINYINT UNSIGNED NOT NULL,
    source TINYINT UNSIGNED NOT NULL,
    reason TINYINT UNSIGNED NOT NULL,
    observation_status TINYINT UNSIGNED NOT NULL,
    modifier_flags SMALLINT UNSIGNED NOT NULL,
    observations BIGINT UNSIGNED NOT NULL,
    zero_applied_observations BIGINT UNSIGNED NOT NULL,
    negative_applied_observations BIGINT UNSIGNED NOT NULL,
    requested_xp BIGINT NOT NULL,
    computed_xp BIGINT NOT NULL,
    applied_xp BIGINT NOT NULL,
    earned_positive_xp BIGINT UNSIGNED NOT NULL,
    death_loss_xp BIGINT UNSIGNED NOT NULL,
    restored_positive_xp BIGINT UNSIGNED NOT NULL,
    linked_observations BIGINT UNSIGNED NOT NULL,
    clock_unknown_observations BIGINT UNSIGNED NOT NULL,
    incident_affected_observations BIGINT UNSIGNED NOT NULL,
    quality_flags BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,cell_digest),
    CONSTRAINT fk_identity_portfolio_xp_coverage FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_identity_coverage (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_identity_portfolio_xp_scope CHECK (definition_version = 3 AND generation <> 0 AND environment_id <> 0 AND season_id <> 0),
    CONSTRAINT chk_identity_portfolio_xp_basis CHECK (((basis BETWEEN 1 AND 3 AND identity_token > 0) OR (basis IN (4,5) AND identity_token = 0))),
    CONSTRAINT chk_identity_portfolio_xp_context CHECK (config_id > 0 AND classifier_version > 0 AND policy_version > 0 AND group_context_mode BETWEEN 0 AND 2 AND partition_kind BETWEEN 0 AND 1 AND (partition_kind <> 0 OR (faction_id = 0 AND level_band = 0 AND group_context_mode = 0))),
    CONSTRAINT chk_identity_portfolio_xp_source CHECK (source BETWEEN 0 AND 12 AND reason BETWEEN 0 AND 6 AND observation_status BETWEEN 1 AND 3 AND modifier_flags <= 511),
    CONSTRAINT chk_identity_portfolio_xp_counts CHECK (zero_applied_observations + negative_applied_observations <= observations AND linked_observations <= observations AND clock_unknown_observations <= observations AND incident_affected_observations <= observations),
    CONSTRAINT chk_identity_portfolio_xp_quality CHECK ((quality_flags & 18446744073172745216) = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
