-- Immutable bounded battle observations, dated presence and identity attribution.
-- Coverage, public rows, retained-source completion and publication status commit
-- together. Metric amounts crossing an unobserved identity boundary stay whole.

CREATE TABLE IF NOT EXISTS telemetry_rollup_battle_coverage (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    input_origin BIGINT UNSIGNED NOT NULL,
    input_watermark BIGINT UNSIGNED NOT NULL,
    source_fact_count INT UNSIGNED NOT NULL,
    source_digest BINARY(32) NOT NULL,
    ownership_count INT UNSIGNED NOT NULL,
    association_count INT UNSIGNED NOT NULL,
    contribution_count INT UNSIGNED NOT NULL,
    quality_flags BIGINT UNSIGNED NOT NULL,
    publication_complete TINYINT UNSIGNED NOT NULL,
    snapshot_digest BINARY(32) NOT NULL,
    battle_row_count INT UNSIGNED NOT NULL,
    actor_row_count INT UNSIGNED NOT NULL,
    contribution_row_count INT UNSIGNED NOT NULL,
    exposure_row_count INT UNSIGNED NOT NULL,
    association_row_count INT UNSIGNED NOT NULL,
    complete_packet_count INT UNSIGNED NOT NULL,
    incomplete_packet_count INT UNSIGNED NOT NULL,
    alias_count INT UNSIGNED NOT NULL,
    canonical_battle_count INT UNSIGNED NOT NULL,
    verified_contribution_links INT UNSIGNED NOT NULL,
    partial_contribution_links INT UNSIGNED NOT NULL,
    observed_present_usec BIGINT UNSIGNED NOT NULL,
    observed_pc_present_usec BIGINT UNSIGNED NOT NULL,
    non_pc_present_usec BIGINT UNSIGNED NOT NULL,
    owned_pc_present_usec BIGINT UNSIGNED NOT NULL,
    unknown_account_pc_present_usec BIGINT UNSIGNED NOT NULL,
    confirmed_controller_pc_present_usec BIGINT UNSIGNED NOT NULL,
    unlinked_controller_pc_present_usec BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id),
    CONSTRAINT fk_battle_coverage_source FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_battle_source (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_battle_coverage_scope CHECK (definition_version = 5 AND generation > 0 AND environment_id > 0 AND season_id > 0),
    CONSTRAINT chk_battle_coverage_source CHECK (input_origin <= input_watermark AND source_fact_count <= 16384 AND source_fact_count <= CAST(input_watermark AS DECIMAL(21,0)) - CAST(input_origin AS DECIMAL(21,0)) AND source_fact_count = ownership_count + association_count + contribution_count),
    CONSTRAINT chk_battle_coverage_complete CHECK (publication_complete = 1),
    CONSTRAINT chk_battle_coverage_rows CHECK (battle_row_count + actor_row_count + contribution_row_count + exposure_row_count + association_row_count <= 4096 AND association_row_count = association_count AND contribution_row_count = contribution_count AND contribution_count = verified_contribution_links + partial_contribution_links),
    CONSTRAINT chk_battle_coverage_history CHECK (complete_packet_count + incomplete_packet_count <= association_count AND canonical_battle_count <= battle_row_count AND alias_count <= battle_row_count),
    CONSTRAINT chk_battle_coverage_presence CHECK (observed_present_usec = observed_pc_present_usec + non_pc_present_usec AND observed_pc_present_usec = owned_pc_present_usec + unknown_account_pc_present_usec AND observed_pc_present_usec = confirmed_controller_pc_present_usec + unlinked_controller_pc_present_usec),
    CONSTRAINT chk_battle_coverage_quality CHECK ((quality_flags & 18446744073172745216) = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS telemetry_rollup_battle_row (
    definition_version INT UNSIGNED NOT NULL,
    generation BIGINT UNSIGNED NOT NULL,
    environment_id BIGINT UNSIGNED NOT NULL,
    season_id BIGINT UNSIGNED NOT NULL,
    row_kind TINYINT UNSIGNED NOT NULL,
    row_key BINARY(32) NOT NULL,
    payload VARBINARY(8192) NOT NULL,
    payload_digest BINARY(32) NOT NULL,
    quality_flags BIGINT UNSIGNED NOT NULL,
    PRIMARY KEY (definition_version,generation,environment_id,season_id,row_kind,row_key),
    CONSTRAINT fk_battle_row_coverage FOREIGN KEY (definition_version,generation,environment_id,season_id) REFERENCES telemetry_rollup_battle_coverage (definition_version,generation,environment_id,season_id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT chk_battle_row_scope CHECK (definition_version = 5 AND generation > 0 AND environment_id > 0 AND season_id > 0),
    CONSTRAINT chk_battle_row_kind CHECK (row_kind BETWEEN 1 AND 5),
    CONSTRAINT chk_battle_row_payload CHECK (OCTET_LENGTH(payload) BETWEEN 1 AND 8192),
    CONSTRAINT chk_battle_row_quality CHECK ((quality_flags & 18446744073172745216) = 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
