#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")

assert_value() {
    local actual
    actual=$("${MYSQL[@]}" -e "$1" | paste -sd'|' -)
    [[ "$actual" == "$2" ]] || { echo "$3" >&2; exit 1; }
}

assert_value 'SELECT CONCAT(column_name,'\'':'\'',CASE WHEN data_type IN ('\''int'\'','\''bigint'\'','\''smallint'\'','\''tinyint'\'') THEN CONCAT(data_type,IF(column_type LIKE '\''%unsigned%'\'','\'' unsigned'\'','\'''\'')) ELSE column_type END,'\'':'\'',is_nullable,'\'':'\'',COALESCE(column_default,'\''NULL'\''),'\'':'\'',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_source_v9'\'' ORDER BY ordinal_position;' 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|input_origin:bigint unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:|source_fact_count:int unsigned:NO:NULL:|source_digest:binary(32):NO:NULL:|interval_count:int unsigned:NO:NULL:|lifecycle_count:int unsigned:NO:NULL:|progression_count:int unsigned:NO:NULL:|ownership_count:int unsigned:NO:NULL:|context_count:int unsigned:NO:NULL:|configuration_chunk_count:int unsigned:NO:NULL:|reference_count:int unsigned:NO:NULL:|reference_digest:binary(32):NO:NULL:|quality_flags:bigint unsigned:NO:NULL:|publication_complete:tinyint unsigned:NO:NULL:' 'telemetry_progression_source_v9 shape differs'
assert_value 'SELECT CONCAT(index_name,'\'':'\'',non_unique,'\'':'\'',index_type,'\'':'\'',GROUP_CONCAT(CONCAT(column_name,'\'':'\'',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '\'','\'')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_source_v9'\'' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0' 'telemetry_progression_source_v9 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_progression_source_v9'\'' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_progression9_source_complete|chk_progression9_source_counts|chk_progression9_source_quality|chk_progression9_source_scope|fk_progression9_source_identity|fk_progression9_source_state' 'telemetry_progression_source_v9 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'\'':'\'',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'\'' '\'','\'''\''),CHAR(96),'\'''\''),'\''('\'','\'''\''),'\'')'\'','\'''\''),CHAR(10),'\'''\'')),'\''octet_length'\'','\''length'\'')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='\''telemetry_progression_source_v9'\'' AND t.constraint_type='\''CHECK'\'' ORDER BY BINARY t.constraint_name;' 'chk_progression9_source_complete:publication_completebetween0and1|chk_progression9_source_counts:input_origin<=input_watermarkandsource_fact_count+reference_count<=16384andsource_fact_count<=castinput_watermarkasdecimal21,0-castinput_originasdecimal21,0andsource_fact_count=interval_count+lifecycle_count+progression_count+ownership_count+context_count+configuration_chunk_count|chk_progression9_source_quality:quality_flags&18446744073172745216=0|chk_progression9_source_scope:definition_version=9andgeneration>0andenvironment_id>0andseason_id>0' 'telemetry_progression_source_v9 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'\'':'\'',k.ordinal_position,'\'':'\'',k.column_name,'\'':'\'',k.referenced_table_name,'\'':'\'',k.referenced_column_name,'\'':'\'',r.update_rule,'\'':'\'',r.delete_rule,'\'':'\'',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='\''telemetry_progression_source_v9'\'' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_progression9_source_identity:1:definition_version:telemetry_generation_identity:definition_version:RESTRICT:RESTRICT:1|fk_progression9_source_identity:2:generation:telemetry_generation_identity:generation:RESTRICT:RESTRICT:1|fk_progression9_source_identity:3:environment_id:telemetry_generation_identity:environment_id:RESTRICT:RESTRICT:1|fk_progression9_source_identity:4:season_id:telemetry_generation_identity:season_id:RESTRICT:RESTRICT:1|fk_progression9_source_state:1:definition_version:telemetry_rollup_state:definition_version:RESTRICT:RESTRICT:1|fk_progression9_source_state:2:generation:telemetry_rollup_state:generation:RESTRICT:RESTRICT:1|fk_progression9_source_state:3:environment_id:telemetry_rollup_state:environment_id:RESTRICT:RESTRICT:1|fk_progression9_source_state:4:season_id:telemetry_rollup_state:season_id:RESTRICT:RESTRICT:1' 'telemetry_progression_source_v9 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'\'':'\'',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_source_v9'\'';' 'InnoDB:utf8mb4_unicode_ci' 'telemetry_progression_source_v9 engine/collation differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_progression_source_v9'\'' AND constraint_type='\''CHECK'\'' AND enforced='\''YES'\'';' '4' 'telemetry_progression_source_v9 checks not enforced'
fi

assert_value 'SELECT CONCAT(column_name,'\'':'\'',CASE WHEN data_type IN ('\''int'\'','\''bigint'\'','\''smallint'\'','\''tinyint'\'') THEN CONCAT(data_type,IF(column_type LIKE '\''%unsigned%'\'','\'' unsigned'\'','\'''\'')) ELSE column_type END,'\'':'\'',is_nullable,'\'':'\'',COALESCE(column_default,'\''NULL'\''),'\'':'\'',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_input_v9'\'' ORDER BY ordinal_position;' 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|ingest_id:bigint unsigned:NO:NULL:|boot_id:bigint unsigned:NO:NULL:|process_id:bigint unsigned:NO:NULL:|record_seq:bigint unsigned:NO:NULL:|record_kind:tinyint unsigned:NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_progression_input_v9 shape differs'
assert_value 'SELECT CONCAT(index_name,'\'':'\'',non_unique,'\'':'\'',index_type,'\'':'\'',GROUP_CONCAT(CONCAT(column_name,'\'':'\'',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '\'','\'')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_input_v9'\'' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,ingest_id:0|uq_progression9_input_replay:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,boot_id:0,process_id:0,record_seq:0' 'telemetry_progression_input_v9 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_progression_input_v9'\'' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_progression9_input_kind|chk_progression9_input_payload|chk_progression9_input_receipt|chk_progression9_input_scope|fk_progression9_input_source|uq_progression9_input_replay' 'telemetry_progression_input_v9 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'\'':'\'',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'\'' '\'','\'''\''),CHAR(96),'\'''\''),'\''('\'','\'''\''),'\'')'\'','\'''\''),CHAR(10),'\'''\'')),'\''octet_length'\'','\''length'\'')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='\''telemetry_progression_input_v9'\'' AND t.constraint_type='\''CHECK'\'' ORDER BY BINARY t.constraint_name;' 'chk_progression9_input_kind:record_kindin1,2,6,9,15,16|chk_progression9_input_payload:lengthpayloadbetween1and8192|chk_progression9_input_receipt:ingest_id>0andboot_id>0andprocess_id>0andrecord_seq>0|chk_progression9_input_scope:definition_version=9andgeneration>0andenvironment_id>0andseason_id>0' 'telemetry_progression_input_v9 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'\'':'\'',k.ordinal_position,'\'':'\'',k.column_name,'\'':'\'',k.referenced_table_name,'\'':'\'',k.referenced_column_name,'\'':'\'',r.update_rule,'\'':'\'',r.delete_rule,'\'':'\'',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='\''telemetry_progression_input_v9'\'' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_progression9_input_source:1:definition_version:telemetry_progression_source_v9:definition_version:RESTRICT:RESTRICT:1|fk_progression9_input_source:2:generation:telemetry_progression_source_v9:generation:RESTRICT:RESTRICT:1|fk_progression9_input_source:3:environment_id:telemetry_progression_source_v9:environment_id:RESTRICT:RESTRICT:1|fk_progression9_input_source:4:season_id:telemetry_progression_source_v9:season_id:RESTRICT:RESTRICT:1' 'telemetry_progression_input_v9 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'\'':'\'',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_input_v9'\'';' 'InnoDB:utf8mb4_unicode_ci' 'telemetry_progression_input_v9 engine/collation differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_progression_input_v9'\'' AND constraint_type='\''CHECK'\'' AND enforced='\''YES'\'';' '4' 'telemetry_progression_input_v9 checks not enforced'
fi

assert_value 'SELECT CONCAT(column_name,'\'':'\'',CASE WHEN data_type IN ('\''int'\'','\''bigint'\'','\''smallint'\'','\''tinyint'\'') THEN CONCAT(data_type,IF(column_type LIKE '\''%unsigned%'\'','\'' unsigned'\'','\'''\'')) ELSE column_type END,'\'':'\'',is_nullable,'\'':'\'',COALESCE(column_default,'\''NULL'\''),'\'':'\'',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_reference_v9'\'' ORDER BY ordinal_position;' 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|ingest_id:bigint unsigned:NO:NULL:|boot_id:bigint unsigned:NO:NULL:|process_id:bigint unsigned:NO:NULL:|record_seq:bigint unsigned:NO:NULL:|record_kind:tinyint unsigned:NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_progression_reference_v9 shape differs'
assert_value 'SELECT CONCAT(index_name,'\'':'\'',non_unique,'\'':'\'',index_type,'\'':'\'',GROUP_CONCAT(CONCAT(column_name,'\'':'\'',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '\'','\'')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_reference_v9'\'' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,ingest_id:0|uq_progression9_reference_replay:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,boot_id:0,process_id:0,record_seq:0' 'telemetry_progression_reference_v9 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_progression_reference_v9'\'' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_progression9_reference_kind|chk_progression9_reference_payload|chk_progression9_reference_receipt|chk_progression9_reference_scope|fk_progression9_reference_source|uq_progression9_reference_replay' 'telemetry_progression_reference_v9 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'\'':'\'',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'\'' '\'','\'''\''),CHAR(96),'\'''\''),'\''('\'','\'''\''),'\'')'\'','\'''\''),CHAR(10),'\'''\'')),'\''octet_length'\'','\''length'\'')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='\''telemetry_progression_reference_v9'\'' AND t.constraint_type='\''CHECK'\'' ORDER BY BINARY t.constraint_name;' 'chk_progression9_reference_kind:record_kindin1,2,6,9,16|chk_progression9_reference_payload:lengthpayloadbetween1and8192|chk_progression9_reference_receipt:ingest_id>0andboot_id>0andprocess_id>0andrecord_seq>0|chk_progression9_reference_scope:definition_version=9andgeneration>0andenvironment_id>0andseason_id>0' 'telemetry_progression_reference_v9 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'\'':'\'',k.ordinal_position,'\'':'\'',k.column_name,'\'':'\'',k.referenced_table_name,'\'':'\'',k.referenced_column_name,'\'':'\'',r.update_rule,'\'':'\'',r.delete_rule,'\'':'\'',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='\''telemetry_progression_reference_v9'\'' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_progression9_reference_source:1:definition_version:telemetry_progression_source_v9:definition_version:RESTRICT:RESTRICT:1|fk_progression9_reference_source:2:generation:telemetry_progression_source_v9:generation:RESTRICT:RESTRICT:1|fk_progression9_reference_source:3:environment_id:telemetry_progression_source_v9:environment_id:RESTRICT:RESTRICT:1|fk_progression9_reference_source:4:season_id:telemetry_progression_source_v9:season_id:RESTRICT:RESTRICT:1' 'telemetry_progression_reference_v9 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'\'':'\'',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='\''telemetry_progression_reference_v9'\'';' 'InnoDB:utf8mb4_unicode_ci' 'telemetry_progression_reference_v9 engine/collation differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_progression_reference_v9'\'' AND constraint_type='\''CHECK'\'' AND enforced='\''YES'\'';' '4' 'telemetry_progression_reference_v9 checks not enforced'
fi

assert_value 'SELECT CONCAT(column_name,'\'':'\'',CASE WHEN data_type IN ('\''int'\'','\''bigint'\'','\''smallint'\'','\''tinyint'\'') THEN CONCAT(data_type,IF(column_type LIKE '\''%unsigned%'\'','\'' unsigned'\'','\'''\'')) ELSE column_type END,'\'':'\'',is_nullable,'\'':'\'',COALESCE(column_default,'\''NULL'\''),'\'':'\'',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_coverage_v9'\'' ORDER BY ordinal_position;' 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|input_origin:bigint unsigned:NO:NULL:|input_watermark:bigint unsigned:NO:NULL:|source_fact_count:int unsigned:NO:NULL:|source_digest:binary(32):NO:NULL:|interval_count:int unsigned:NO:NULL:|lifecycle_count:int unsigned:NO:NULL:|progression_count:int unsigned:NO:NULL:|ownership_count:int unsigned:NO:NULL:|context_count:int unsigned:NO:NULL:|configuration_chunk_count:int unsigned:NO:NULL:|reference_count:int unsigned:NO:NULL:|reference_digest:binary(32):NO:NULL:|quality_flags:bigint unsigned:NO:NULL:|publication_complete:tinyint unsigned:NO:NULL:|snapshot_digest:binary(32):NO:NULL:|context_row_count:int unsigned:NO:NULL:|milestone_row_count:int unsigned:NO:NULL:|rotation_row_count:int unsigned:NO:NULL:|effort_row_count:int unsigned:NO:NULL:|portfolio_row_count:int unsigned:NO:NULL:|unknown_context_count:int unsigned:NO:NULL:|completed_milestone_count:int unsigned:NO:NULL:|unfinished_milestone_count:int unsigned:NO:NULL:|censored_milestone_count:int unsigned:NO:NULL:|qualified_full_stage_count:int unsigned:NO:NULL:|qualified_rate_cell_count:int unsigned:NO:NULL:' 'telemetry_rollup_progression_coverage_v9 shape differs'
assert_value 'SELECT CONCAT(index_name,'\'':'\'',non_unique,'\'':'\'',index_type,'\'':'\'',GROUP_CONCAT(CONCAT(column_name,'\'':'\'',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '\'','\'')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_coverage_v9'\'' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0' 'telemetry_rollup_progression_coverage_v9 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_coverage_v9'\'' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_progression9_coverage_complete|chk_progression9_coverage_counts|chk_progression9_coverage_detail|chk_progression9_coverage_quality|chk_progression9_coverage_rows|chk_progression9_coverage_scope|fk_progression9_coverage_source' 'telemetry_rollup_progression_coverage_v9 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'\'':'\'',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'\'' '\'','\'''\''),CHAR(96),'\'''\''),'\''('\'','\'''\''),'\'')'\'','\'''\''),CHAR(10),'\'''\'')),'\''octet_length'\'','\''length'\'')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='\''telemetry_rollup_progression_coverage_v9'\'' AND t.constraint_type='\''CHECK'\'' ORDER BY BINARY t.constraint_name;' 'chk_progression9_coverage_complete:publication_complete=1|chk_progression9_coverage_counts:input_origin<=input_watermarkandsource_fact_count+reference_count<=16384andsource_fact_count<=castinput_watermarkasdecimal21,0-castinput_originasdecimal21,0andsource_fact_count=interval_count+lifecycle_count+progression_count+ownership_count+context_count+configuration_chunk_count|chk_progression9_coverage_detail:context_row_count=context_countandunknown_context_count<=context_row_countandcompleted_milestone_count+unfinished_milestone_count+censored_milestone_count=milestone_row_countandqualified_full_stage_count<=completed_milestone_countandqualified_rate_cell_count<=portfolio_row_count|chk_progression9_coverage_quality:quality_flags&18446744073172745216=0|chk_progression9_coverage_rows:context_row_count+milestone_row_count+rotation_row_count+effort_row_count+portfolio_row_count<=4096|chk_progression9_coverage_scope:definition_version=9andgeneration>0andenvironment_id>0andseason_id>0' 'telemetry_rollup_progression_coverage_v9 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'\'':'\'',k.ordinal_position,'\'':'\'',k.column_name,'\'':'\'',k.referenced_table_name,'\'':'\'',k.referenced_column_name,'\'':'\'',r.update_rule,'\'':'\'',r.delete_rule,'\'':'\'',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='\''telemetry_rollup_progression_coverage_v9'\'' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_progression9_coverage_source:1:definition_version:telemetry_progression_source_v9:definition_version:RESTRICT:RESTRICT:1|fk_progression9_coverage_source:2:generation:telemetry_progression_source_v9:generation:RESTRICT:RESTRICT:1|fk_progression9_coverage_source:3:environment_id:telemetry_progression_source_v9:environment_id:RESTRICT:RESTRICT:1|fk_progression9_coverage_source:4:season_id:telemetry_progression_source_v9:season_id:RESTRICT:RESTRICT:1' 'telemetry_rollup_progression_coverage_v9 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'\'':'\'',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_coverage_v9'\'';' 'InnoDB:utf8mb4_unicode_ci' 'telemetry_rollup_progression_coverage_v9 engine/collation differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_coverage_v9'\'' AND constraint_type='\''CHECK'\'' AND enforced='\''YES'\'';' '6' 'telemetry_rollup_progression_coverage_v9 checks not enforced'
fi

assert_value 'SELECT CONCAT(column_name,'\'':'\'',CASE WHEN data_type IN ('\''int'\'','\''bigint'\'','\''smallint'\'','\''tinyint'\'') THEN CONCAT(data_type,IF(column_type LIKE '\''%unsigned%'\'','\'' unsigned'\'','\'''\'')) ELSE column_type END,'\'':'\'',is_nullable,'\'':'\'',COALESCE(column_default,'\''NULL'\''),'\'':'\'',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_row_v9'\'' ORDER BY ordinal_position;' 'definition_version:int unsigned:NO:NULL:|generation:bigint unsigned:NO:NULL:|environment_id:bigint unsigned:NO:NULL:|season_id:bigint unsigned:NO:NULL:|row_kind:tinyint unsigned:NO:NULL:|row_key:binary(32):NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:|quality_flags:bigint unsigned:NO:NULL:' 'telemetry_rollup_progression_row_v9 shape differs'
assert_value 'SELECT CONCAT(index_name,'\'':'\'',non_unique,'\'':'\'',index_type,'\'':'\'',GROUP_CONCAT(CONCAT(column_name,'\'':'\'',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '\'','\'')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_row_v9'\'' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:definition_version:0,generation:0,environment_id:0,season_id:0,row_kind:0,row_key:0' 'telemetry_rollup_progression_row_v9 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_row_v9'\'' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_progression9_row_kind|chk_progression9_row_payload|chk_progression9_row_quality|chk_progression9_row_scope|fk_progression9_row_coverage' 'telemetry_rollup_progression_row_v9 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'\'':'\'',REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'\'' '\'','\'''\''),CHAR(96),'\'''\''),'\''('\'','\'''\''),'\'')'\'','\'''\''),CHAR(10),'\'''\'')),'\''octet_length'\'','\''length'\'')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='\''telemetry_rollup_progression_row_v9'\'' AND t.constraint_type='\''CHECK'\'' ORDER BY BINARY t.constraint_name;' 'chk_progression9_row_kind:row_kindbetween1and5|chk_progression9_row_payload:lengthpayloadbetween1and8192|chk_progression9_row_quality:quality_flags&18446744073172745216=0|chk_progression9_row_scope:definition_version=9andgeneration>0andenvironment_id>0andseason_id>0' 'telemetry_rollup_progression_row_v9 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'\'':'\'',k.ordinal_position,'\'':'\'',k.column_name,'\'':'\'',k.referenced_table_name,'\'':'\'',k.referenced_column_name,'\'':'\'',r.update_rule,'\'':'\'',r.delete_rule,'\'':'\'',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='\''telemetry_rollup_progression_row_v9'\'' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_progression9_row_coverage:1:definition_version:telemetry_rollup_progression_coverage_v9:definition_version:RESTRICT:RESTRICT:1|fk_progression9_row_coverage:2:generation:telemetry_rollup_progression_coverage_v9:generation:RESTRICT:RESTRICT:1|fk_progression9_row_coverage:3:environment_id:telemetry_rollup_progression_coverage_v9:environment_id:RESTRICT:RESTRICT:1|fk_progression9_row_coverage:4:season_id:telemetry_rollup_progression_coverage_v9:season_id:RESTRICT:RESTRICT:1' 'telemetry_rollup_progression_row_v9 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'\'':'\'',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_row_v9'\'';' 'InnoDB:utf8mb4_unicode_ci' 'telemetry_rollup_progression_row_v9 engine/collation differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='\''telemetry_rollup_progression_row_v9'\'' AND constraint_type='\''CHECK'\'' AND enforced='\''YES'\'';' '4' 'telemetry_rollup_progression_row_v9 checks not enforced'
fi

assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_source_insert'\'';' 'telemetry_progression_source_v9:BEFORE:INSERT:ROW:2f69bb70a6e38357ae9ef770669cf1e6b95f920f744654618916fa7ccc738ef9' 'telemetry_progression9_source_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_source_update'\'';' 'telemetry_progression_source_v9:BEFORE:UPDATE:ROW:37b8ad906a6104121ac02b22d041ccfb461981f973c4e2fbad977d7c18300fbf' 'telemetry_progression9_source_update differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_source_delete'\'';' 'telemetry_progression_source_v9:BEFORE:DELETE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_source_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_input_insert'\'';' 'telemetry_progression_input_v9:BEFORE:INSERT:ROW:e7101b2d06cfef60244c98b5eff2e49ae6f4d120a6be40e0009a682f53b70816' 'telemetry_progression9_input_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_input_update'\'';' 'telemetry_progression_input_v9:BEFORE:UPDATE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_input_update differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_input_delete'\'';' 'telemetry_progression_input_v9:BEFORE:DELETE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_input_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_reference_insert'\'';' 'telemetry_progression_reference_v9:BEFORE:INSERT:ROW:e7101b2d06cfef60244c98b5eff2e49ae6f4d120a6be40e0009a682f53b70816' 'telemetry_progression9_reference_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_reference_update'\'';' 'telemetry_progression_reference_v9:BEFORE:UPDATE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_reference_update differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_reference_delete'\'';' 'telemetry_progression_reference_v9:BEFORE:DELETE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_reference_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_coverage_insert'\'';' 'telemetry_rollup_progression_coverage_v9:BEFORE:INSERT:ROW:c0631abb4f920dc6d9c0378baf7c233ecb18dcc5ba2198fd1d483f8dc165775f' 'telemetry_progression9_coverage_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_coverage_update'\'';' 'telemetry_rollup_progression_coverage_v9:BEFORE:UPDATE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_coverage_update differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_coverage_delete'\'';' 'telemetry_rollup_progression_coverage_v9:BEFORE:DELETE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_coverage_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_row_insert'\'';' 'telemetry_rollup_progression_row_v9:BEFORE:INSERT:ROW:7da28b78d65eacb7495272b25706e194c46cf465ef2b2935e918e39f7abab23d' 'telemetry_progression9_row_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_row_update'\'';' 'telemetry_rollup_progression_row_v9:BEFORE:UPDATE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_row_update differs'
assert_value 'SELECT CONCAT(event_object_table,'\'':'\'',action_timing,'\'':'\'',event_manipulation,'\'':'\'',action_orientation,'\'':'\'',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'\'' '\'','\'''\''),CHAR(96),'\'''\''),CHAR(10),'\'''\'')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='\''telemetry_progression9_row_delete'\'';' 'telemetry_rollup_progression_row_v9:BEFORE:DELETE:ROW:11f86b9c9a777350c6448c280d2128550f78363e2a6d536a7f572d775bde952d' 'telemetry_progression9_row_delete differs'
assert_value 'SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND event_object_table IN ('\''telemetry_progression_source_v9'\'','\''telemetry_progression_input_v9'\'','\''telemetry_progression_reference_v9'\'','\''telemetry_rollup_progression_coverage_v9'\'','\''telemetry_rollup_progression_row_v9'\'');' '15' 'progression publication trigger inventory differs'
echo 'Progression definition 9 retained source and publication schema verified.'
