#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")

assert_value() {
    local actual
    actual=$("${MYSQL[@]}" -e "$1" | paste -sd'|' -)
    [[ "$actual" == "$2" ]] || { echo "$3" >&2; printf 'Actual metadata: %s\n' "$actual" >&2; exit 1; }
}

assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_cut_v2'"'"' ORDER BY ordinal_position;' 'cut_id:binary(32):NO:NULL:|definition_version:int unsigned:NO:NULL:|captured_utc_usec:bigint unsigned:NO:NULL:|source_digest:binary(32):NO:NULL:|selected_count:int unsigned:NO:NULL:|source_count:int unsigned:NO:NULL:|reserved_bytes:int unsigned:NO:NULL:|sealed:tinyint unsigned:NO:NULL:|discovery_bucket:tinyint unsigned:YES:NULL:|discovery_cursor:binary(16):YES:NULL:|discovery_limit:smallint unsigned:YES:NULL:|discovery_through:binary(16):YES:NULL:|discovery_upper:binary(16):YES:NULL:' 'telemetry_reward_cut_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_cut_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:cut_id:0 'telemetry_reward_cut_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_cut_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_cut_bounds|chk_reward2_cut_discovery|chk_reward2_cut_identity|chk_reward2_cut_sealed' 'telemetry_reward_cut_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_cut_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_cut_bounds:selected_count<=16384andsource_count<=16384andreserved_bytesbetween4096and33554432|chk_reward2_cut_discovery:discovery_bucketisnullanddiscovery_cursorisnullanddiscovery_limitisnullanddiscovery_throughisnullanddiscovery_upperisnullordiscovery_bucketisnotnullanddiscovery_cursorisnotnullanddiscovery_limitbetween1and666anddiscovery_upperisnotnullanddiscovery_cursor=unhexrepeatchar48,32orordsubstrdiscovery_cursor,1,1=discovery_bucketanddiscovery_upper=unhexrepeatchar48,32orordsubstrdiscovery_upper,1,1=discovery_bucketanddiscovery_throughisnullordiscovery_upper=discovery_throughanddiscovery_cursor<=discovery_through|chk_reward2_cut_identity:definition_version=2andcut_id=source_digestandcaptured_utc_usec>0|chk_reward2_cut_sealed:sealedbetween0and1' 'telemetry_reward_cut_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_cut_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' '' 'telemetry_reward_cut_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_cut_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_cut_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_cut_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 4 'telemetry_reward_cut_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_selection_v2'"'"' ORDER BY ordinal_position;' 'cut_id:binary(32):NO:NULL:|selection_index:smallint unsigned:NO:NULL:|operation_id:binary(16):NO:NULL:' 'telemetry_reward_selection_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_selection_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:cut_id:0,selection_index:0|uq_reward2_selection_operation:0:BTREE:cut_id:0,operation_id:0' 'telemetry_reward_selection_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_selection_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_selection_index|chk_reward2_selection_operation|fk_reward2_selection_cut|uq_reward2_selection_operation' 'telemetry_reward_selection_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_selection_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_selection_index:selection_index<16384|chk_reward2_selection_operation:operation_id<>unhexrepeatchar48,32' 'telemetry_reward_selection_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_selection_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' fk_reward2_selection_cut:1:cut_id:telemetry_reward_cut_v2:cut_id:RESTRICT:RESTRICT:1 'telemetry_reward_selection_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_selection_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_selection_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_selection_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 2 'telemetry_reward_selection_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_source_v2'"'"' ORDER BY ordinal_position;' 'cut_id:binary(32):NO:NULL:|source_index:smallint unsigned:NO:NULL:|source_table:varbinary(64):NO:NULL:|source_key:varbinary(128):NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_reward_source_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_source_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:cut_id:0,source_index:0|idx_reward2_source_payloads:1:BTREE:source_table:0,source_key:0,payload_digest:0,cut_id:0|uq_reward2_source_identity:0:BTREE:cut_id:0,source_table:0,source_key:0' 'telemetry_reward_source_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_source_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_source_index|chk_reward2_source_key|chk_reward2_source_payload|fk_reward2_source_cut|uq_reward2_source_identity' 'telemetry_reward_source_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_source_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_source_index:source_index<16384|chk_reward2_source_key:lengthsource_tablebetween1and64andlengthsource_keybetween1and128|chk_reward2_source_payload:lengthpayloadbetween1and8192' 'telemetry_reward_source_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_source_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' fk_reward2_source_cut:1:cut_id:telemetry_reward_cut_v2:cut_id:RESTRICT:RESTRICT:1 'telemetry_reward_source_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_source_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_source_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_source_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 3 'telemetry_reward_source_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_cut_insert'"'"';' telemetry_reward_cut_v2:BEFORE:INSERT:ROW:e6f9a784b4cd8f64351f7346d6f363f819fa8a4816102655c8eef3f86fc3bf71 'telemetry_reward2_cut_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_cut_update'"'"';' telemetry_reward_cut_v2:BEFORE:UPDATE:ROW:c141093e21b31df5ed29d371f490605def293ea0a6129976bec10bc49ba8b443 'telemetry_reward2_cut_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_cut_delete'"'"';' telemetry_reward_cut_v2:BEFORE:DELETE:ROW:4d50b086774d2b48cb33a426a0022000b8b899330b974de81c30bb2d341e7ad0 'telemetry_reward2_cut_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_selection_insert'"'"';' telemetry_reward_selection_v2:BEFORE:INSERT:ROW:d9e31c8bb3d36a848adaebbd81d472bdf643da3188693658e63e6c008b467ce7 'telemetry_reward2_selection_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_source_insert'"'"';' telemetry_reward_source_v2:BEFORE:INSERT:ROW:0ee34f0457906f1f95fcfde82b45b3f86c4bb99a99b3bbab083df32820f00999 'telemetry_reward2_source_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_selection_update'"'"';' telemetry_reward_selection_v2:BEFORE:UPDATE:ROW:07a47a1ac8662394a6b1f7a5b366e954aa371b9f4f2a75635059ccc10463ba27 'telemetry_reward2_selection_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_selection_delete'"'"';' telemetry_reward_selection_v2:BEFORE:DELETE:ROW:07a47a1ac8662394a6b1f7a5b366e954aa371b9f4f2a75635059ccc10463ba27 'telemetry_reward2_selection_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_source_update'"'"';' telemetry_reward_source_v2:BEFORE:UPDATE:ROW:03921dca43e7eed917e2d23c6ef1d08c88bd8cac5bf801aa7225f766f8b02295 'telemetry_reward2_source_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_source_delete'"'"';' telemetry_reward_source_v2:BEFORE:DELETE:ROW:03921dca43e7eed917e2d23c6ef1d08c88bd8cac5bf801aa7225f766f8b02295 'telemetry_reward2_source_delete differs'
assert_value 'SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND event_object_table IN ('"'"'telemetry_reward_cut_v2'"'"','"'"'telemetry_reward_selection_v2'"'"','"'"'telemetry_reward_source_v2'"'"');' 9 'canonical retention trigger inventory differs'
echo 'Canonical reward definition 2 private schema verified.'
