#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")

assert_value() {
    local actual
    actual=$("${MYSQL[@]}" -e "$1" | paste -sd'|' -)
    [[ "$actual" == "$2" ]] || { echo "$3" >&2; printf 'Actual metadata: %s\n' "$actual" >&2; exit 1; }
}

assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_v2'"'"' ORDER BY ordinal_position;' 'scan_id:binary(16):NO:NULL:|definition_version:int unsigned:NO:NULL:|revision:bigint unsigned:NO:NULL:|next_bucket:tinyint unsigned:NO:NULL:|provisional:tinyint unsigned:NO:NULL:' 'telemetry_reward_sweep_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:scan_id:0 'telemetry_reward_sweep_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_sweep_definition' 'telemetry_reward_sweep_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_sweep_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' chk_reward2_sweep_definition:definition_version=2andprovisional=1 'telemetry_reward_sweep_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_sweep_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' '' 'telemetry_reward_sweep_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_sweep_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 1 'telemetry_reward_sweep_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_bucket_v2'"'"' ORDER BY ordinal_position;' 'scan_id:binary(16):NO:NULL:|bucket:tinyint unsigned:NO:NULL:|cursor_operation:binary(16):NO:NULL:|pass_upper:binary(16):YES:NULL:|completed_passes:bigint unsigned:NO:NULL:|failures:bigint unsigned:NO:NULL:|last_revision:bigint unsigned:NO:NULL:|last_cut:binary(32):YES:NULL:' 'telemetry_reward_sweep_bucket_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_bucket_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:scan_id:0,bucket:0|idx_reward2_bucket_cut:1:BTREE:last_cut:0' 'telemetry_reward_sweep_bucket_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_bucket_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_bucket_range|fk_reward2_bucket_cut|fk_reward2_bucket_scan' 'telemetry_reward_sweep_bucket_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_sweep_bucket_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_bucket_range:cursor_operation=unhexrepeatchar48,32andpass_upperisnullorpass_upperisnotnullandcursor_operation<=pass_upperandordsubstrcursor_operation,1,1=bucketandordsubstrpass_upper,1,1=bucket' 'telemetry_reward_sweep_bucket_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_sweep_bucket_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_reward2_bucket_cut:1:last_cut:telemetry_reward_cut_v2:cut_id:RESTRICT:RESTRICT:1|fk_reward2_bucket_scan:1:scan_id:telemetry_reward_sweep_v2:scan_id:RESTRICT:RESTRICT:1' 'telemetry_reward_sweep_bucket_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_bucket_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_sweep_bucket_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_bucket_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 1 'telemetry_reward_sweep_bucket_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_step_v2'"'"' ORDER BY ordinal_position;' 'scan_id:binary(16):NO:NULL:|revision:bigint unsigned:NO:NULL:|bucket:tinyint unsigned:NO:NULL:|status:tinyint unsigned:NO:NULL:|attempted_utc_usec:bigint unsigned:NO:NULL:|cut_id:binary(32):YES:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_reward_sweep_step_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_step_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:scan_id:0,revision:0|idx_reward2_step_cut:1:BTREE:cut_id:0' 'telemetry_reward_sweep_step_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_step_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_step_payload|chk_reward2_step_revision|chk_reward2_step_status|fk_reward2_step_cut|fk_reward2_step_scan' 'telemetry_reward_sweep_step_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_sweep_step_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_step_payload:lengthpayloadbetween1and8192|chk_reward2_step_revision:revision>0andattempted_utc_usec>0|chk_reward2_step_status:statusbetween1and2andcut_idisnotnullorstatusbetween3and6andcut_idisnull' 'telemetry_reward_sweep_step_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_sweep_step_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_reward2_step_cut:1:cut_id:telemetry_reward_cut_v2:cut_id:RESTRICT:RESTRICT:1|fk_reward2_step_scan:1:scan_id:telemetry_reward_sweep_v2:scan_id:RESTRICT:RESTRICT:1' 'telemetry_reward_sweep_step_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_step_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_sweep_step_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_sweep_step_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 3 'telemetry_reward_sweep_step_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_sweep_insert'"'"';' telemetry_reward_sweep_v2:BEFORE:INSERT:ROW:1aba671b4e3b51ecc64b01e0204695b69291be9c6f27d1ab1b06116cb81ac67b 'telemetry_reward2_sweep_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_sweep_update'"'"';' telemetry_reward_sweep_v2:BEFORE:UPDATE:ROW:a3f792d896675a497d9495ffa26d4899f427ac4675d40c693653270e4f1501ff 'telemetry_reward2_sweep_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_sweep_delete'"'"';' telemetry_reward_sweep_v2:BEFORE:DELETE:ROW:9a2a44e45814d9d0e16b97537b394c280a4550a5a8ebe124d394240f36e8e20d 'telemetry_reward2_sweep_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_bucket_insert'"'"';' telemetry_reward_sweep_bucket_v2:BEFORE:INSERT:ROW:c0957f0c54a82b8ce6f2ccec757a38ecbec8f5d625b18039cb8755935c1ca1c1 'telemetry_reward2_bucket_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_bucket_update'"'"';' telemetry_reward_sweep_bucket_v2:BEFORE:UPDATE:ROW:7bcf48f205c14a39ce8a4cbbbdeff8ae3ea62f5c6e5b49a136c0adb7e5700197 'telemetry_reward2_bucket_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_bucket_delete'"'"';' telemetry_reward_sweep_bucket_v2:BEFORE:DELETE:ROW:3aee60ea59586dbc0c430ea1b7b829201ef128491d3b2c388ded0d99debd2c8b 'telemetry_reward2_bucket_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_step_insert'"'"';' telemetry_reward_sweep_step_v2:BEFORE:INSERT:ROW:b26c1657994fa880149a2fd79f38f12049e22ba64235fb89b318dbd3f43d312b 'telemetry_reward2_step_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_step_update'"'"';' telemetry_reward_sweep_step_v2:BEFORE:UPDATE:ROW:8827eda0224d181ece5fc2b0e37072e2e0085dcb9473cb4aa0ffd0d5f0728b9a 'telemetry_reward2_step_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_step_delete'"'"';' telemetry_reward_sweep_step_v2:BEFORE:DELETE:ROW:8827eda0224d181ece5fc2b0e37072e2e0085dcb9473cb4aa0ffd0d5f0728b9a 'telemetry_reward2_step_delete differs'
assert_value 'SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND event_object_table IN ('"'"'telemetry_reward_sweep_v2'"'"','"'"'telemetry_reward_sweep_bucket_v2'"'"','"'"'telemetry_reward_sweep_step_v2'"'"');' 9 'canonical retention trigger inventory differs'
echo 'Canonical reward definition 2 private schema verified.'
