#!/usr/bin/env bash
set -euo pipefail
: "${DB_HOST:?}" "${DB_USER:?}" "${DB_PASSWD:?}" "${DB_NAME:?}"
export MYSQL_PWD="$DB_PASSWD"
if [[ -n "${DB_SOCKET:-}" ]]; then
    [[ "$DB_SOCKET" == /* ]] || { echo 'database socket must be absolute' >&2; exit 1; }
    CONNECTION=(--protocol=socket --socket="$DB_SOCKET")
else
    CONNECTION=(--protocol=tcp -h "$DB_HOST" -P "${DB_PORT:-3306}")
    help=$(mysql --no-defaults --help)
    if [[ "$DB_HOST" == 127.0.0.1 || "$DB_HOST" == localhost || "$DB_HOST" == ::1 ]]; then
        if [[ "$help" == *--ssl-mode* ]]; then CONNECTION+=(--ssl-mode=PREFERRED); else CONNECTION+=(--skip-ssl); fi
    else
        [[ "${DB_TLS:-}" == TRUE && -f "${DB_SSL_CA:-}" ]] || { echo 'remote verification requires TLS and a CA file' >&2; exit 1; }
        if [[ "$help" == *--ssl-mode* ]]; then
            CONNECTION+=(--ssl-mode=VERIFY_IDENTITY --ssl-ca="$DB_SSL_CA")
        elif [[ "$help" == *--ssl-verify-server-cert* ]]; then
            CONNECTION+=(--ssl-verify-server-cert --ssl-ca="$DB_SSL_CA")
        else
            echo 'database client cannot verify remote identity' >&2; exit 1
        fi
    fi
fi
MYSQL=(timeout 30 mysql --no-defaults --connect-timeout=10 "${CONNECTION[@]}" -u "$DB_USER" -N -B --raw "$DB_NAME")

assert_value() {
    local actual
    actual=$("${MYSQL[@]}" -e "$1" | paste -sd'|' -)
    [[ "$actual" == "$2" ]] || { echo "$3" >&2; printf 'Actual metadata: %s\n' "$actual" >&2; exit 1; }
}

assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_generation_v2'"'"' ORDER BY ordinal_position;' 'generation_id:binary(16):NO:NULL:|definition_version:int unsigned:NO:NULL:|snapshot_utc_usec:bigint unsigned:NO:NULL:|cut_count:smallint unsigned:NO:NULL:|binding_count:smallint unsigned:NO:NULL:|event_count:smallint unsigned:NO:NULL:|health_count:smallint unsigned:NO:NULL:|reserved_bytes:int unsigned:NO:NULL:|evidence_digest:binary(32):NO:NULL:|projection_digest:binary(32):NO:NULL:|health_evidence_digest:binary(32):NO:NULL:|health_projection_digest:binary(32):NO:NULL:|coverage_payload:varbinary(8192):NO:NULL:|coverage_digest:binary(32):NO:NULL:|phase:tinyint unsigned:NO:NULL:' 'telemetry_reward_generation_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_generation_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:generation_id:0 'telemetry_reward_generation_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_generation_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_generation_counts|chk_reward2_generation_health|chk_reward2_generation_payload|chk_reward2_generation_phase|chk_reward2_generation_version' 'telemetry_reward_generation_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_generation_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_generation_counts:cut_countbetween1and256andbinding_countbetweencut_countand16384andevent_count<=2000andreserved_bytesbetween4096and33554432|chk_reward2_generation_health:health_countin0,257|chk_reward2_generation_payload:lengthcoverage_payloadbetween1and8192|chk_reward2_generation_phase:phasebetween0and2|chk_reward2_generation_version:definition_version=2andsnapshot_utc_usec>0' 'telemetry_reward_generation_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_generation_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' '' 'telemetry_reward_generation_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_generation_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_generation_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_generation_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 5 'telemetry_reward_generation_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_binding_v2'"'"' ORDER BY ordinal_position;' 'generation_id:binary(16):NO:NULL:|binding_index:smallint unsigned:NO:NULL:|binding_kind:tinyint unsigned:NO:NULL:|cut_id:binary(32):NO:NULL:|source_index:smallint unsigned:YES:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_reward_binding_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_binding_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' 'PRIMARY:0:BTREE:generation_id:0,binding_index:0|idx_reward2_binding_cut:1:BTREE:cut_id:0|idx_reward2_binding_source:1:BTREE:cut_id:0,source_index:0' 'telemetry_reward_binding_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_binding_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_binding_index|chk_reward2_binding_kind|fk_reward2_binding_cut|fk_reward2_binding_generation|fk_reward2_binding_source' 'telemetry_reward_binding_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_binding_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_binding_index:binding_index<16384|chk_reward2_binding_kind:binding_kind=1andsource_indexisnullandpayload_digest=cut_idorbinding_kind=2andsource_indexisnotnullandsource_index<16384' 'telemetry_reward_binding_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_binding_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' 'fk_reward2_binding_cut:1:cut_id:telemetry_reward_cut_v2:cut_id:RESTRICT:RESTRICT:1|fk_reward2_binding_generation:1:generation_id:telemetry_reward_generation_v2:generation_id:RESTRICT:RESTRICT:1|fk_reward2_binding_source:1:cut_id:telemetry_reward_source_v2:cut_id:RESTRICT:RESTRICT:1|fk_reward2_binding_source:2:source_index:telemetry_reward_source_v2:source_index:RESTRICT:RESTRICT:1' 'telemetry_reward_binding_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_binding_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_binding_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_binding_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 2 'telemetry_reward_binding_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_private_v2'"'"' ORDER BY ordinal_position;' 'generation_id:binary(16):NO:NULL:|event_index:smallint unsigned:NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_reward_event_private_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_private_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:generation_id:0,event_index:0 'telemetry_reward_event_private_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_private_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_private_event_index|chk_reward2_private_event_payload|fk_reward2_private_event_generation' 'telemetry_reward_event_private_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_event_private_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_private_event_index:event_index<2000|chk_reward2_private_event_payload:lengthpayloadbetween1and8192' 'telemetry_reward_event_private_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_event_private_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' fk_reward2_private_event_generation:1:generation_id:telemetry_reward_generation_v2:generation_id:RESTRICT:RESTRICT:1 'telemetry_reward_event_private_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_private_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_event_private_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_private_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 2 'telemetry_reward_event_private_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_coverage_v2'"'"' ORDER BY ordinal_position;' 'generation_id:binary(16):NO:NULL:|definition_version:int unsigned:NO:NULL:|snapshot_utc_usec:bigint unsigned:NO:NULL:|binding_count:smallint unsigned:NO:NULL:|event_count:smallint unsigned:NO:NULL:|health_count:smallint unsigned:NO:NULL:|evidence_digest:binary(32):NO:NULL:|projection_digest:binary(32):NO:NULL:|health_evidence_digest:binary(32):NO:NULL:|health_projection_digest:binary(32):NO:NULL:|coverage_payload:varbinary(8192):NO:NULL:|coverage_digest:binary(32):NO:NULL:|complete:tinyint unsigned:NO:NULL:' 'telemetry_reward_coverage_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_coverage_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:generation_id:0 'telemetry_reward_coverage_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_coverage_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_coverage_complete|chk_reward2_coverage_health|chk_reward2_coverage_payload|chk_reward2_coverage_version|fk_reward2_coverage_generation' 'telemetry_reward_coverage_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_coverage_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_coverage_complete:completebetween0and1|chk_reward2_coverage_health:health_countin0,257|chk_reward2_coverage_payload:lengthcoverage_payloadbetween1and8192|chk_reward2_coverage_version:definition_version=2andsnapshot_utc_usec>0andevent_count<=2000andbinding_countbetween1and16384' 'telemetry_reward_coverage_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_coverage_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' fk_reward2_coverage_generation:1:generation_id:telemetry_reward_generation_v2:generation_id:RESTRICT:RESTRICT:1 'telemetry_reward_coverage_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_coverage_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_coverage_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_coverage_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 4 'telemetry_reward_coverage_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_v2'"'"' ORDER BY ordinal_position;' 'generation_id:binary(16):NO:NULL:|event_index:smallint unsigned:NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_reward_event_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:generation_id:0,event_index:0 'telemetry_reward_event_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_public_event_index|chk_reward2_public_event_payload|fk_reward2_public_event_coverage' 'telemetry_reward_event_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_event_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_public_event_index:event_index<2000|chk_reward2_public_event_payload:lengthpayloadbetween1and8192' 'telemetry_reward_event_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_event_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' fk_reward2_public_event_coverage:1:generation_id:telemetry_reward_coverage_v2:generation_id:RESTRICT:RESTRICT:1 'telemetry_reward_event_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_event_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_event_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 2 'telemetry_reward_event_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_private_v2'"'"' ORDER BY ordinal_position;' 'generation_id:binary(16):NO:NULL:|health_index:smallint unsigned:NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:|projection_payload:varbinary(8192):NO:NULL:|projection_digest:binary(32):NO:NULL:' 'telemetry_reward_health_private_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_private_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:generation_id:0,health_index:0 'telemetry_reward_health_private_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_private_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_private_health_index|chk_reward2_private_health_payload|chk_reward2_private_health_projection|fk_reward2_private_health_generation' 'telemetry_reward_health_private_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_health_private_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_private_health_index:health_index<257|chk_reward2_private_health_payload:lengthpayloadbetween1and8192|chk_reward2_private_health_projection:lengthprojection_payloadbetween1and8192' 'telemetry_reward_health_private_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_health_private_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' fk_reward2_private_health_generation:1:generation_id:telemetry_reward_generation_v2:generation_id:RESTRICT:RESTRICT:1 'telemetry_reward_health_private_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_private_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_health_private_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_private_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 3 'telemetry_reward_health_private_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(column_name,'"'"':'"'"',CASE WHEN data_type IN ('"'"'int'"'"','"'"'bigint'"'"','"'"'smallint'"'"','"'"'tinyint'"'"') THEN CONCAT(data_type,IF(column_type LIKE '"'"'%unsigned%'"'"','"'"' unsigned'"'"','"'"''"'"')) ELSE column_type END,'"'"':'"'"',is_nullable,'"'"':'"'"',COALESCE(column_default,'"'"'NULL'"'"'),'"'"':'"'"',extra) FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_v2'"'"' ORDER BY ordinal_position;' 'generation_id:binary(16):NO:NULL:|health_index:smallint unsigned:NO:NULL:|payload:varbinary(8192):NO:NULL:|payload_digest:binary(32):NO:NULL:' 'telemetry_reward_health_v2 shape differs'
assert_value 'SELECT CONCAT(index_name,'"'"':'"'"',non_unique,'"'"':'"'"',index_type,'"'"':'"'"',GROUP_CONCAT(CONCAT(column_name,'"'"':'"'"',COALESCE(sub_part,0)) ORDER BY seq_in_index SEPARATOR '"'"','"'"')) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_v2'"'"' GROUP BY index_name,non_unique,index_type ORDER BY BINARY index_name;' PRIMARY:0:BTREE:generation_id:0,health_index:0 'telemetry_reward_health_v2 indexes differ'
assert_value 'SELECT constraint_name FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_v2'"'"' ORDER BY BINARY constraint_name;' 'PRIMARY|chk_reward2_public_health_index|chk_reward2_public_health_payload|fk_reward2_public_health_generation' 'telemetry_reward_health_v2 constraints differ'
assert_value 'SELECT CONCAT(t.constraint_name,'"'"':'"'"',REPLACE(REPLACE(LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(c.check_clause,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),'"'"'('"'"','"'"''"'"'),'"'"')'"'"','"'"''"'"'),CHAR(10),'"'"''"'"')),'"'"'octet_length'"'"','"'"'length'"'"'),'"'"'substring'"'"','"'"'substr'"'"')) FROM information_schema.table_constraints t JOIN information_schema.check_constraints c ON c.constraint_schema=t.constraint_schema AND c.constraint_name=t.constraint_name WHERE t.constraint_schema=DATABASE() AND t.table_name='"'"'telemetry_reward_health_v2'"'"' AND t.constraint_type='"'"'CHECK'"'"' ORDER BY BINARY t.constraint_name;' 'chk_reward2_public_health_index:health_index<257|chk_reward2_public_health_payload:lengthpayloadbetween1and8192' 'telemetry_reward_health_v2 checks differ'
assert_value 'SELECT CONCAT(k.constraint_name,'"'"':'"'"',k.ordinal_position,'"'"':'"'"',k.column_name,'"'"':'"'"',k.referenced_table_name,'"'"':'"'"',k.referenced_column_name,'"'"':'"'"',r.update_rule,'"'"':'"'"',r.delete_rule,'"'"':'"'"',BINARY k.referenced_table_schema=BINARY DATABASE()) FROM information_schema.key_column_usage k JOIN information_schema.referential_constraints r ON r.constraint_schema=k.constraint_schema AND r.constraint_name=k.constraint_name WHERE k.constraint_schema=DATABASE() AND k.table_name='"'"'telemetry_reward_health_v2'"'"' AND k.referenced_table_name IS NOT NULL ORDER BY BINARY k.constraint_name,k.ordinal_position;' fk_reward2_public_health_generation:1:generation_id:telemetry_reward_coverage_v2:generation_id:RESTRICT:RESTRICT:1 'telemetry_reward_health_v2 foreign keys differ'
assert_value 'SELECT CONCAT(engine,'"'"':'"'"',table_collation) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_v2'"'"';' InnoDB:utf8mb4_unicode_ci 'telemetry_reward_health_v2 engine differs'
if [[ $("${MYSQL[@]}" -e 'SELECT VERSION();') != *MariaDB* ]]; then
assert_value 'SELECT COUNT(*) FROM information_schema.table_constraints WHERE constraint_schema=DATABASE() AND table_name='"'"'telemetry_reward_health_v2'"'"' AND constraint_type='"'"'CHECK'"'"' AND enforced='"'"'YES'"'"';' 2 'telemetry_reward_health_v2 checks not enforced'
fi
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_generation_insert'"'"';' telemetry_reward_generation_v2:BEFORE:INSERT:ROW:ecfcf95dc3bbc0fcd254bd33225fc82754c8e7a817a815bb64c97450b09b58c5 'telemetry_reward2_generation_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_generation_update'"'"';' telemetry_reward_generation_v2:BEFORE:UPDATE:ROW:2ab26a9b10817d75b62d5beee4ef56b68abb0498e5271f9c3f0f4f5e99403ddb 'telemetry_reward2_generation_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_generation_delete'"'"';' telemetry_reward_generation_v2:BEFORE:DELETE:ROW:e4b814619d45e4291644a0a67629b38750f14fc3381cd9158eb50f767ffd79d0 'telemetry_reward2_generation_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_binding_insert'"'"';' telemetry_reward_binding_v2:BEFORE:INSERT:ROW:f69018cade1d6b3ef48f74c8ecccf024848e9fb8557d236a04be727763c1b4a0 'telemetry_reward2_binding_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_private_event_insert'"'"';' telemetry_reward_event_private_v2:BEFORE:INSERT:ROW:33cf7e981454eee87fa2292ebd1031f60be4124f61e786ed3f303f582832dd47 'telemetry_reward2_private_event_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_coverage_insert'"'"';' telemetry_reward_coverage_v2:BEFORE:INSERT:ROW:65249d2637714d345a025e36579d35b6839ef9b98219d3172b417294744661a6 'telemetry_reward2_coverage_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_coverage_update'"'"';' telemetry_reward_coverage_v2:BEFORE:UPDATE:ROW:f42ba1eb5ddca3a48710ff8dd30026778dc3088ba5beab5d286f048ddba28bf8 'telemetry_reward2_coverage_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_public_event_insert'"'"';' telemetry_reward_event_v2:BEFORE:INSERT:ROW:30b11a38599a8b0822d11db8ce60b2b6922b982ef3941e611fc53526bc09e532 'telemetry_reward2_public_event_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_binding_update'"'"';' telemetry_reward_binding_v2:BEFORE:UPDATE:ROW:d30b575f0e2654d417533b0d58fb4f32c7077bdd1f1167fdf011a7b277fe81dd 'telemetry_reward2_binding_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_binding_delete'"'"';' telemetry_reward_binding_v2:BEFORE:DELETE:ROW:d30b575f0e2654d417533b0d58fb4f32c7077bdd1f1167fdf011a7b277fe81dd 'telemetry_reward2_binding_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_private_event_update'"'"';' telemetry_reward_event_private_v2:BEFORE:UPDATE:ROW:d30b575f0e2654d417533b0d58fb4f32c7077bdd1f1167fdf011a7b277fe81dd 'telemetry_reward2_private_event_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_private_event_delete'"'"';' telemetry_reward_event_private_v2:BEFORE:DELETE:ROW:d30b575f0e2654d417533b0d58fb4f32c7077bdd1f1167fdf011a7b277fe81dd 'telemetry_reward2_private_event_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_coverage_delete'"'"';' telemetry_reward_coverage_v2:BEFORE:DELETE:ROW:d30b575f0e2654d417533b0d58fb4f32c7077bdd1f1167fdf011a7b277fe81dd 'telemetry_reward2_coverage_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_public_event_update'"'"';' telemetry_reward_event_v2:BEFORE:UPDATE:ROW:d30b575f0e2654d417533b0d58fb4f32c7077bdd1f1167fdf011a7b277fe81dd 'telemetry_reward2_public_event_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_public_event_delete'"'"';' telemetry_reward_event_v2:BEFORE:DELETE:ROW:d30b575f0e2654d417533b0d58fb4f32c7077bdd1f1167fdf011a7b277fe81dd 'telemetry_reward2_public_event_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_private_health_insert'"'"';' telemetry_reward_health_private_v2:BEFORE:INSERT:ROW:7a480ca706ad687b5b8d9947281a99745299a8a2ee25e1e5083acf1f539d5d17 'telemetry_reward2_private_health_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_public_health_insert'"'"';' telemetry_reward_health_v2:BEFORE:INSERT:ROW:1f59b2d61cd8d114b5d5ad6072b746f59281c9d2f0468365399325708bfc85bc 'telemetry_reward2_public_health_insert differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_private_health_update'"'"';' telemetry_reward_health_private_v2:BEFORE:UPDATE:ROW:51dbe86dd3d102f85b1c795fe070f6930d93261f3f53be420cdeb114e23f0edc 'telemetry_reward2_private_health_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_private_health_delete'"'"';' telemetry_reward_health_private_v2:BEFORE:DELETE:ROW:51dbe86dd3d102f85b1c795fe070f6930d93261f3f53be420cdeb114e23f0edc 'telemetry_reward2_private_health_delete differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_public_health_update'"'"';' telemetry_reward_health_v2:BEFORE:UPDATE:ROW:51dbe86dd3d102f85b1c795fe070f6930d93261f3f53be420cdeb114e23f0edc 'telemetry_reward2_public_health_update differs'
assert_value 'SELECT CONCAT(event_object_table,'"'"':'"'"',action_timing,'"'"':'"'"',event_manipulation,'"'"':'"'"',action_orientation,'"'"':'"'"',SHA2(LOWER(REPLACE(REPLACE(REPLACE(action_statement,'"'"' '"'"','"'"''"'"'),CHAR(96),'"'"''"'"'),CHAR(10),'"'"''"'"')),256)) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND trigger_name='"'"'telemetry_reward2_public_health_delete'"'"';' telemetry_reward_health_v2:BEFORE:DELETE:ROW:51dbe86dd3d102f85b1c795fe070f6930d93261f3f53be420cdeb114e23f0edc 'telemetry_reward2_public_health_delete differs'
assert_value 'SELECT COUNT(*) FROM information_schema.triggers WHERE trigger_schema=DATABASE() AND event_object_table IN ('"'"'telemetry_reward_generation_v2'"'"','"'"'telemetry_reward_binding_v2'"'"','"'"'telemetry_reward_event_private_v2'"'"','"'"'telemetry_reward_coverage_v2'"'"','"'"'telemetry_reward_event_v2'"'"','"'"'telemetry_reward_health_private_v2'"'"','"'"'telemetry_reward_health_v2'"'"');' 21 'canonical retention trigger inventory differs'
echo 'Canonical reward definition 2 private schema verified.'
