"""Small deterministic aggregate fixture for the #269 report contracts."""
from __future__ import annotations

from datetime import date

TARGET_SCOPE = (1, 7, 8, 9)


def state_row(*, generation: int = 7, publication_status: int = 1) -> dict:
    return {
        "definition_version": 1,
        "generation": generation,
        "environment_id": 8,
        "season_id": 9,
        "input_watermark": 42,
        "publication_status": publication_status,
        "coverage_start_utc_usec": 1_704_067_200_000_000,
        "coverage_end_utc_usec": 1_704_153_600_000_000,
        "quality_flags": 0,
        "provisional": 1,
        "rebuild_from_ingest_id": 0,
        "rebuild_through_ingest_id": 42,
    }


def session_rows() -> list[dict]:
    return [
        {
            "subject_id": 1001,
            "pid": 501,
            "session_boot_id": 11,
            "session_process_id": 21,
            "session_seq": 1,
            "latest_checkpoint_revision": 3,
            "connected_usec": 3_000_000,
            "active_usec": 2_000_000,
            "idle_usec": 1_000_000,
            "unknown_usec": 0,
            "resident_usec": 3_000_000,
            "linkdead_usec": 0,
            "covered_connected_usec": 3_000_000,
            "covered_active_usec": 2_000_000,
            "covered_idle_usec": 1_000_000,
            "covered_unknown_usec": 0,
            "covered_resident_usec": 3_000_000,
            "covered_linkdead_usec": 0,
            "attributable_usec": 2_500_000,
            "observed_intervals": 3,
            "entered": 1,
            "exited": 1,
            "end_reason": 1,
            "quality_flags": 0,
            "input_watermark": 41,
            "provisional": 1,
        },
        {
            "subject_id": 1001,
            "pid": 501,
            "session_boot_id": 12,
            "session_process_id": 21,
            "session_seq": 2,
            "latest_checkpoint_revision": 0,
            "connected_usec": 0,
            "active_usec": 0,
            "idle_usec": 0,
            "unknown_usec": 0,
            "resident_usec": 0,
            "linkdead_usec": 0,
            "covered_connected_usec": 4_000_000,
            "covered_active_usec": 1_000_000,
            "covered_idle_usec": 2_000_000,
            "covered_unknown_usec": 1_000_000,
            "covered_resident_usec": 5_000_000,
            "covered_linkdead_usec": 1_000_000,
            "attributable_usec": 0,
            "observed_intervals": 4,
            "entered": 1,
            "exited": 0,
            "end_reason": 0,
            "quality_flags": 1 << 21,
            "input_watermark": 42,
            "provisional": 1,
        },
        {
            "subject_id": 1002,
            "pid": 502,
            "session_boot_id": 13,
            "session_process_id": 22,
            "session_seq": 1,
            "latest_checkpoint_revision": 0,
            "connected_usec": 0,
            "active_usec": 0,
            "idle_usec": 0,
            "unknown_usec": 0,
            "resident_usec": 0,
            "linkdead_usec": 0,
            "covered_connected_usec": 1_000_000,
            "covered_active_usec": 1_000_000,
            "covered_idle_usec": 0,
            "covered_unknown_usec": 0,
            "covered_resident_usec": 1_000_000,
            "covered_linkdead_usec": 0,
            "attributable_usec": 1_000_000,
            "observed_intervals": 1,
            "entered": 1,
            "exited": 1,
            "end_reason": 2,
            "quality_flags": 0,
            "input_watermark": 42,
            "provisional": 1,
        },
    ]


def cohort_rows() -> list[dict]:
    return [
        {
            "utc_day": date(2024, 1, 1),
            "level_band": 50,
            "class_id": 2,
            "race_id": 3,
            "faction_id": 4,
            "zone_vnum": 100,
            "config_id": 700,
            "category": 2,
            "duration_usec": 2_000_000,
            "attributable_usec": 2_000_000,
            "observed_intervals": 2,
            "subject_count": 1,
            "session_count": 1,
            "quality_flags": 0,
            "input_watermark": 41,
            "provisional": 1,
        },
        {
            "utc_day": date(2024, 1, 2),
            "level_band": 50,
            "class_id": 2,
            "race_id": 3,
            "faction_id": 4,
            "zone_vnum": 100,
            "config_id": 700,
            "category": 2,
            "duration_usec": 3_000_000,
            "attributable_usec": 2_500_000,
            "observed_intervals": 3,
            "subject_count": 1,
            "session_count": 1,
            "quality_flags": 0,
            "input_watermark": 42,
            "provisional": 1,
        },
        {
            "utc_day": date(2024, 1, 2),
            "level_band": 60,
            "class_id": 5,
            "race_id": 6,
            "faction_id": 8,
            "zone_vnum": 200,
            "config_id": 701,
            "category": 1,
            "duration_usec": 4_000_000,
            "attributable_usec": 0,
            "observed_intervals": 4,
            "subject_count": 1,
            "session_count": 1,
            "quality_flags": 1 << 21,
            "input_watermark": 42,
            "provisional": 1,
        },
        {
            "utc_day": date(1000, 1, 1),
            "level_band": 0,
            "class_id": 0,
            "race_id": 0,
            "faction_id": 0,
            "zone_vnum": -1,
            "config_id": 702,
            "category": 0,
            "duration_usec": 1_000_000,
            "attributable_usec": 0,
            "observed_intervals": 1,
            "subject_count": 1,
            "session_count": 1,
            "quality_flags": 1 << 16,
            "input_watermark": 42,
            "provisional": 1,
        },
    ]


def member_rows() -> list[dict]:
    rows: list[dict] = []
    for subject, session in (
        (1001, (11, 21, 1)),
        (1001, (12, 21, 2)),
        (1002, (13, 22, 1)),
    ):
        rows.append(
            {
                "utc_day": date(2024, 1, 2),
                "level_band": 50 if subject == 1001 else 60,
                "class_id": 2 if subject == 1001 else 5,
                "race_id": 3 if subject == 1001 else 6,
                "faction_id": 4 if subject == 1001 else 8,
                "zone_vnum": 100 if subject == 1001 else 200,
                "config_id": 700 if subject == 1001 else 701,
                "category": 2 if subject == 1001 else 1,
                "membership_kind": 2,
                "subject_id": subject,
                "session_boot_id": session[0],
                "session_process_id": session[1],
                "session_seq": session[2],
                "duration_usec": 1_000_000,
                "attributable_usec": 500_000 if subject == 1001 else 0,
                "observed_intervals": 1,
                "quality_flags": 0 if subject == 1001 else 1 << 21,
                "input_watermark": 42,
            }
        )
    return rows


def expected_playtime_summary() -> dict:
    return {
        "session_count": 3,
        "subject_count": 2,
        "covered_resident_usec": 9_000_000,
        "covered_active_usec": 4_000_000,
        "attributable_usec": 3_500_000,
        "observed_intervals": 8,
    }
