#!/bin/bash
# Non-production warning inventory helper.
#
# Performs a clean build with the legacy warning exception categories enabled as
# non-fatal warnings and reports deduplicated diagnostic counts by category and
# by file.  Used by docs/ongoing-projects/compiler-legacy-exceptions-cleanup-plan.md
# to track progress; it never produces a shippable binary configuration.
#
# Usage: scripts/warning-inventory.sh [-j N] [-o OUTDIR]

set -u

JOBS=$(nproc 2>/dev/null || echo 2)
OUTDIR="build/warning-inventory"

while [ $# -gt 0 ]; do
    case "$1" in
        -j) JOBS="$2"; shift 2 ;;
        -o) OUTDIR="$2"; shift 2 ;;
        -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

cd "$(dirname "$0")/.." || exit 1
mkdir -p "$OUTDIR"

RAW="$OUTDIR/raw.log"
REPORT="$OUTDIR/report.txt"

CATEGORIES="write-strings unused-parameter unused-variable unused-but-set-variable missing-field-initializers unused-function"

ENABLE=""
for c in $CATEGORIES; do
    ENABLE="$ENABLE -W$c"
done

# Drop -Werror so the inventory build links, and turn the legacy exceptions into
# explicit enables.
BASE_WARNINGS=$(sed -n '/^WARNING_FLAGS/,/[^\\]$/p' src/Makefile \
    | sed 's/^WARNING_FLAGS[[:space:]]*=//' | tr -d '\\' | tr '\n' ' ' \
    | sed 's/-Werror//')

make -C src clean >/dev/null 2>&1
make -C src -j"$JOBS" \
    WARNING_FLAGS="$BASE_WARNINGS -fdiagnostics-column-unit=byte" \
    LEGACY_WARNING_EXCEPTIONS="$ENABLE" \
    >"$RAW" 2>&1
BUILD_STATUS=$?

{
    echo "Warning inventory"
    echo "Generated by scripts/warning-inventory.sh"
    echo "Compiler: $(g++ --version | head -1)"
    echo "Enabled categories:$ENABLE"
    echo "Base warning flags: $BASE_WARNINGS"
    echo "Build exit status: $BUILD_STATUS"
    echo
} >"$REPORT"

# Deduplicate on file:line:col + message text.
DEDUP="$OUTDIR/dedup.txt"
grep -E '^[^ ]+:[0-9]+:[0-9]+: warning: .*\[-W' "$RAW" | sort -u >"$DEDUP"

{
    echo "== Counts by category =="
    printf '%-32s %8s %8s\n' "category" "warnings" "files"
    total=0
    for c in $CATEGORIES; do
        n=$(grep -c -- "\[-W$c\]" "$DEDUP")
        f=$(grep -- "\[-W$c\]" "$DEDUP" | cut -d: -f1 | sort -u | wc -l)
        printf '%-32s %8d %8d\n' "$c" "$n" "$f"
        total=$((total + n))
    done
    printf '%-32s %8d %8s\n' "TOTAL" "$total" "-"
    echo
    echo "== Counts by file (legacy categories only) =="
    grep -E -- "\[-W(${CATEGORIES// /|})\]" "$DEDUP" | cut -d: -f1 | sort | uniq -c | sort -rn
    echo
    echo "== Per-file per-category =="
    for c in $CATEGORIES; do
        echo "-- $c --"
        grep -- "\[-W$c\]" "$DEDUP" | cut -d: -f1 | sort | uniq -c | sort -rn
    done
} >>"$REPORT"

cat "$REPORT"
echo
echo "raw log:  $RAW"
echo "dedup:    $DEDUP"
echo "report:   $REPORT"
